### ISSUE TITLE
Need Help over editing configurations in ubuntu 14.04

### ISSUE THREAD

**Issue by fayizan** [AJS-development/Ogar-unlimited#1012]
I m using digital ocean vps and I really don't know about ubuntu operating codes,someone pls help me
Skype fayizbe

**Comment by Megabyte918** [comment]
https://www.sublimetext.com/3
theres an ubuntu installation there, once installed you should be able to read the configs correctly

**Comment by fayizan** [comment]
how do I install this using commands in ubuntu

**Comment by Megabyte918** [comment]
i have no idea i dont have ubuntu =P
but i found something [here](http://askubuntu.com/questions/172698/how-do-i-install-sublime-text-2-3) that might help

**Comment by systemroot** [comment]
1. Install nodejs login as root.
apt-get update && apt-get upgrade -y
apt-get install build-essential libssl-dev -y
curl https://raw.githubusercontent.com/creationix/nvm/v0.16.1/install.sh | sh
source ~/.profile
nvm install 5.9.0
nvm use 5.9.0
nvm alias default 5.9.0
nvm use default
npm install -g express

2. Get and install Ogar.
apt-get install git
git clone https://github.com/AJS-development/Ogar-unlimited.git
cd Ogar-unlimited/src
npm install
node index.js

**Comment by fayizan** [comment]
@systemroot Thank you 
what about CentOS ,same commands as ubuntu..?

**Comment by fayizan** [comment]
![screenshot_9](https://cloud.githubusercontent.com/assets/19163419/16051619/1bbaf8b6-327e-11e6-8da4-b2e83764e0a8.jpg)

which one I have to select

**Comment by LegitSoulja** [comment]
I recommend the base of redhat

**Comment by fayizan** [comment]
I m using digitalocean which doesn't have redhat os

**Comment by fayizan** [comment]
@systemroot  how to setup OgarUL in Cent OS

**Comment by systemroot** [comment]
@fayizan login as root

cd ~
wget http://nodejs.org/dist/v0.10.30/node-v0.10.30-linux-x64.tar.gz
sudo tar --strip-components 1 -xzvf node-v* -C /usr/local
node -v

this will install an old version of node, but well now upgrade it to 5.9.0

npm cache clean -f
npm install -g n
n 5.9.0

**Comment by fayizan** [comment]
@systemroot thank u so much but why the hell the console is deadly slow..??!!!

**Comment by fayizan** [comment]
@systemroot could u please tell me how to setup Ogar unlimited in Redhat Os
![screenshot_13](https://cloud.githubusercontent.com/assets/19163419/16077408/3b325c64-3316-11e6-9366-9812fb5cd28e.jpg)

**Comment by fayizan** [comment]
@LegitSoulja hope u know about redhat setup u talked about it above

**Comment by systemroot** [comment]
@fayizan test internet connection on your vps :/ 
and sorry but i have not work before with Redhat and i don't know how to install node or anythink else!

**Comment by fayizan** [comment]
@systemroot  no problem cent os is soo good working awesome
but digitalocean.com console is deadly slow , what about suse linux..?

**Comment by fayizan** [comment]
I have amazon account so only I asking u,please don't say microsoft windows 2012 I know about it
which one is best
![screenshot_2](https://cloud.githubusercontent.com/assets/19163419/16084340/11c35c1e-3336-11e6-8573-fda969385411.jpg)

**Comment by systemroot** [comment]
@fayizan try to connect it via Putty, Slow console i think will be the same in all OS's, 
Because is for reason off Slow Internet on VPS, 
if is needed too much time to install a program this is because off low RAM and CPU.

**Comment by fayizan** [comment]
digitalocean not offering to connect their server via Putty,they have their own console

**Comment by fayizan** [comment]
is there any way to connect server through putty without private key..?

**Comment by systemroot** [comment]
@fayizan hmm :/ sorry i have not use them before i'm an ovh and scaleway client :confused: 
and for as time as they have ports open i thing yes you can connect those
do you have any option to set key's when you create a vps ?!
you can generate a key with puttygen, because to connect vps with privat key or without a key you need to set a public key for securicy reason.
![](http://image.prntscr.com/image/844ba3b2637f48bdacbd63376952ce57.png)
write a Key passphrase (a password)
save privat key on pc, 
now copy that Public key all 
login on vps as root and open 
if is centOS install nano
yum install nano
cd ~
nano .ssh/authorized_keys
paste that public key which you copy from puttygen like this
![](http://image.prntscr.com/image/765ab3ee0e3f477aafa652b0e626dfb0.png)
to close nano press CTRL+X and Y to save changes.

now you can login with that privat key, but also you can connect without a key!
nano /etc/ssh/sshd_config
scroll it and find where is **PermitRootLogin**
and change it like this 
![](http://image.prntscr.com/image/95e0621089424c4a8d50c5b44e538655.png)

scroll down again and find where is **PasswordAuthentication**
and change it like this 
![](http://image.prntscr.com/image/f9ff18b946524cd28cb892b236ba7678.png)

CTRL+X and Y
now write those commands
service ssh restart
passwd
(write a password) 
And try to connect vps with putty :)

**Comment by fayizan** [comment]
I got it and I will try it 
@systemroot Thank you

**Comment by fayizan** [comment]
@systemroot why closing the putty ends the ogarul server..?

**Comment by LegitSoulja** [comment]
@fayizan that's just like you closing an active running terminal/console. Just think about this.
- How would you go back and stop the server? Or go back and look at the console? You can't. 

I'd prefer red hat since it's the base of them all too be honest with you. If you want to use Remote Desktop I recommend an older version of Windows server.

**Comment by fayizan** [comment]
@LegitSoulja the digital ocean has a native console which we can close the console and we can open it back without ending the session

**Comment by fayizan** [comment]
@LegitSoulja It is impossible to install edge browser in windows 7  :(

**Comment by LegitSoulja** [comment]
Putty doesn't do that. Putty pretty much starts a new terminal each time you connect.

**Comment by systemroot** [comment]
@fayizan  sorry for late reply i didn't see this!
**screen** then **node index.js**
you can close putty or anything else. just dont use **exit**
to get console back login on server and wrote **screen -r**

**Comment by fayizan** [comment]
Ty @systemroot

**Comment by fayizan** [comment]
@systemroot  why screen terminates after 6 hour of running ogarul in Centos..?? please help me 
Auto terminating is  sooo irritating..!!!

**Comment by systemroot** [comment]
@fayizan is closed just screen or screen + ogar srv is closed?!

**Comment by fayizan** [comment]
Screen +ogarul terminates automatically after 6 hours uptime

**Comment by systemroot** [comment]
@fayizan Have you as your provider for this? "Is here any sleep or refresh/restart time for my servers?  Because i want to run an app 24/7 and this app is closed automatically every 6/h"
.
Maybe is problem with your provider. I have run screen 24/7 without problems even if i can't access screen session ogarul is still up and running normally! (CentOS, Ubuntu And Windows.)

**Comment by fayizan** [comment]
They said there is nothing problem on their side and so I looked into my ogarul once again,what I did was `screen node index.js` and now I started server using `screen ./start.sh` , lets see what happens after 6 hours 
Thanks for replying @systemroot

**Comment by fayizan** [comment]
@systemroot  heared Debian os is much better for gameservers,can u please explain the steps to install ogarul in debian os

**Comment by systemroot** [comment]
@fayizan 
**`cd ~/`**
**`wget https://raw.githubusercontent.com/NoiseControllers/ogar-unlimited-autoinstall/master/Debian/inode.sh`**
**`chmod +x inode.sh`**
**`./inode.sh`**
**`git clone https://github.com/AJS-development/Ogar-unlimited.git`**
**`cd Ogar-unlimited/src && npm install`**
**`node index.js`**

**Comment by fayizan** [comment]
@systemroot thank you so much,how could I install node v6.3.1...??

**Comment by systemroot** [comment]
**npm cache clean -f**
**npm install -g n**
**n 6.3.1**
**sudo ln -sf /usr/local/n/versions/node/6.3.1/bin/node /usr/bin/node**
**npm config set prefix /usr/local**

Let me to know if is any problem.

**Comment by LegitSoulja** [comment]
Um..

```
sudo ln -s /usr/local/bin/node /usr/bin/node
sudo ln -s /usr/local/lib/node /usr/lib/node
sudo ln -s /usr/local/bin/npm /usr/bin/npm
sudo ln -s /usr/local/bin/node-waf /usr/bin/node-waf
```
Install correctly.. Otherwise you'll be stuck to run OgarUL in-correctly. I'm not for sure if less information as you provided will work or not.

**Comment by fayizan** [comment]
Thank you @systemroot and @LegitSoulja
