### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by devin1155** [AJS-development/Ogar-unlimited#1021]
how about teaching us to use statistics. Some people dont know how to

**Comment by LegitSoulja** [comment]
There's really nothing too much about statistics. How about you read the config file that came with? 

Everything is self explanatory, but it's not noob proof. 

All you do is install the plugin, and change your server name and you are done. 

Make sure that your stat port is open because it's mainly used for tracking, and to determine if your server is online or not.

If you are using something like c9 with a domain for example exampleserver-1.c9.io or something like that you add that for a **customip** and set usevpsip to 0. 

Other than that if you are using your main vps ip, or computer ip don't change nothing except your server name and make sure your ports are open.
