### ISSUE TITLE
why..... 

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#1022]
why the splits are short?
why the ogar is lagg?
because , they make a stable version? no lagy , no bugs

i have 16gb dedicated and have lagg , the ogar is really  unstable..

**Comment by David1ali12** [comment]
So much lag , jxcore solution ?!

**Comment by fayizan** [comment]
editing the configs really make lag

**Comment by RelTakeover** [comment]
You can edit the fps , but still does not work really fluid

you can edit garbagecollect to 0 , and the same lagg

i do not know "jxcore solution"


It would be good to see a stable release

**Comment by RelTakeover** [comment]
the splits are rare

**Comment by CalvinDKHD** [comment]
jxcore runs multithreaded which works, it will do so it doesnt lag. BUT! I dont know how to apply it to OgarUL.

**Comment by fayizan** [comment]
No one knows about JXCore Implementation,Don't ask about that here 
this is the answer which I get before a month so contributors won't help regarding JXCore in OgarUL

**Comment by CalvinDKHD** [comment]
Uhh, why not? Node isnt multithreaded. It kinda sucks.

**Comment by firelightning13** [comment]
Just install JXCore, it will apply to OgarUL automatically

**Comment by firelightning13** [comment]
But not sure that is actually working
(Im using my phone, rip my laptop :( )

**Comment by CalvinDKHD** [comment]
No, if u just install it that doesnt work. Cause it will still run using node.
You would have to make it run using JX

**Comment by raphyjb** [comment]
Firelightning could u help me on skype? skype: raphy.jb

**Comment by David1ali12** [comment]
@DEVS I found when some connects with low speed internet it makes your server laggy 
I connected with slow internet my vps became 1200ms ping but when I connected with fast internet my vps ping was 93ms ping thats why players can make lag

**Comment by RelTakeover** [comment]
stupid comment

**Comment by Megabyte918** [comment]
@David1ali12 ive also noticed this and experienced it myself

**Comment by LegitSoulja** [comment]
Jxcore is really easy to install and use. No you just can't install jxcore and think it will work because jxcore has to be installed and part of your path environment for you to run a script/ogarul using jxcore. 

Note that the garbage collector still exist, but you won't actually need it if jxcore keeps your memory down. I personally myself for the things I do you shouldn't stress your cores out with nodejs. Maybe 1 or 2 cores but not all of them unless you have a strict vps just for running just ogarul :/. 

With the garbage collector it takes a certain amount of time before it initiate, so that means lag can happen every second, or minute but jxcore keeps it low and steady running smoothly.

I'll make a tutorial soon in how to install and use jxcore properly for GNU/Linux and Windows.
