### ISSUE TITLE
How to create server on ogarul.io?

### ISSUE THREAD

**Issue by Peppyrotom** [AJS-development/Ogar-unlimited#1035]
How to create server for ogarul.io?
I saw some people did their own server and hosting it on ogarul.io.
Can anyone give a guide or tutorial for this?

**Comment by LegitSoulja** [comment]
@Peppyrotom ogarul.io does not provide server hosting... **yet*

**Comment by Peppyrotom** [comment]
@LegitSoulja What about the statistics plugin?

**Comment by CalvinDKHD** [comment]
@Peppyrotom It works on c9.

**Comment by LegitSoulja** [comment]
@Peppyrotom Statistics servers are both listed on http://ogarul.io and http://play.ogarul.tk

With c9 since there's no ip but a workspace name/domain you can use really easy.

When you install statistics check out the config file. Set your custom server name.

Change: **usevpsip** to 0

Set **customip** to your c9 workspace/domain and you are done. Don't add no ports to the custom ip because it grabs your server port and stat port automatically.

**Comment by Peppyrotom** [comment]
@LegitSoulja I have done that but my server doesnt appear in ogarul.io. Did i have to install Client plugin?

**Comment by LegitSoulja** [comment]
@Peppyrotom show me your config, and no you didn't enter it wrong.

Your server will be listed here http://stats.ogarul.tk when added and if online.

**Comment by David1ali12** [comment]
I used stats for my server hosted on c9.io it does  work it's online but shows as offline Idk Why

**Comment by LegitSoulja** [comment]
@David1ali12 I don't even remember if I applied cross domain Ajax, I pretty sure I did but I'll go back and make sure

**Comment by Peppyrotom** [comment]
@LegitSoulja //
//  PLEASE NOTE. SERVER STAT PORT HAS TO BE OPEN FOR THIS TO WORK!. DO NOT USE LOCALHOST INFORMATION,
//  THIS IS PUBLIC INFORMATION PEOPLE WILL NEED TO JOIN YOUR SERVER. 
//
//  BY YOU AGREEING, AND INSTALLING THIS PLUGIN, YOU ARE ALLOWING OGAR UNLIMITED TO STORE YOUR SERVER INFORMATION FOR PUBLIC USE FOR GAME CONNECTIVITY, AND STATS, AND OTHER GAME INFORMATION.
//  IF YOU HAVE CONCERNS, CONTACT USE HERE https://github.com/AJS-development/OgarUL-Plugin-Library/issues
//

// Your unique specfic name for your server :) **YOU HAVE TO CHANGE THIS**
serverName = "FFA Asia Server"

// Make this 0 to Disable alerts abouts stats on connections and updates via statistics
alerts = 1

// If enabled(1) your ip or VPS ip will be updated. Use (0) to use customip/domain
usevpsip = 0

// This can only be used if usevpsip is 0. Mainly your IP your friends will connect to. NOT LOCAL HOST!
customip = "ogarhost-peppaogar
.c9users.io"

// Make this 1 to be able to opt out and keep the plugin, and remove all statistic information.
optout = 0

// IF you are using a client other than play.ogarul.tk, enter here. Ex("example.com") Don't add /?ip!. it is not required. But your server will be used this to redirect.
// by default, if clientlink is null/empty/contains no char player.ogarul.tk client will be used instead of agar.io or any other.
clientlink = ""
// If you want to see more information output in your console you might not even understand but be my guest..
debug = 0

**Comment by Peppyrotom** [comment]
@LegitSoulja What l have done are
1) Create public node.js workspace on c9
2) npm install
3) sudo node src/index.js
4)plugin install Statistics
5) exit the ogar server
6) sudo chmod ugo+rw src/plugins (give a read/write permission)
7) edit config.ini as above
8) save and run index.js with sudo node
9) my server isnt appear in stat.ogarul.tk
Have i done something wrong?

**Comment by LegitSoulja** [comment]
@Peppyrotom what does statistics output say when it started?

**Comment by Peppyrotom** [comment]
@LegitSoulja Ive just been blocked by Cloud9 now.
Are there any free vps service i can use?

**Comment by Peppyrotom** [comment]
@LegitSoulja 
[Statistics] No recent updates :)
{
Server Name: FFA for Pepp
Server Ip: ogar-peppapig.c9users.io
{

[Statistics] 
 Added this new server to OgarUnlimited Statistics!. 

             Please read the rules  ->  http://stats.ogarul.tk/ban/
[Statistics] , Updated Ping

**Comment by LegitSoulja** [comment]
Your server is listed

**Comment by Agarian** [comment]
Wait in http://stats.ogarul.tk/ban/ it says "Your server does not meet the required requirements"? Lol it would be better to just put "requirements" instead of "required requirements"?

**Comment by Peppyrotom** [comment]
I think my major problem is c9 account blocking. After run the server first time,next time i enter the workspace, my account is immediatly blocked.
Are there any free service like c9?

**Comment by Agarian** [comment]
BECAUSE RUNNINH OGAR SERVERS ON C9 IS AGAINST ITS TERMS OF SERVICE unfortunately.

**Comment by LegitSoulja** [comment]
@Agarian im just that cool to so "required requirements" haha. Ill change it later.

**Comment by yohano** [comment]
I no view my server In the list, Please help me LegitSoulja D:

**Comment by aymanio** [comment]
how to use c9

**Comment by aymanio** [comment]
for private servers

**Comment by aymanio** [comment]
cuz ùy friends cant join with hamachi

**Comment by LegitSoulja** [comment]
@aymanio don't use c9.

**Comment by aymanio** [comment]
k

**Comment by aymanio** [comment]
what i use ?

**Comment by aymanio** [comment]
plz talk fast

**Comment by aymanio** [comment]
hello

**Comment by aymanio** [comment]
?

**Comment by aymanio** [comment]
help plz

**Comment by ItzLevvie** [comment]
^^ Buy a VPS

**Comment by aymanio** [comment]
i dont have money

**Comment by LegitSoulja** [comment]
Well you're out of luck mr.

**Comment by LegitSoulja** [comment]
And please don't spam, or you'll just be ignored.

**Comment by aymanio** [comment]
shut the fuck up

**Comment by aymanio** [comment]
im here for ask

**Comment by aymanio** [comment]
or for fucking dhut up?

**Comment by aymanio** [comment]
uj

**Comment by LegitSoulja** [comment]
@AJS-development

**Comment by Megabyte918** [comment]
wow.

**Comment by SharkFinPro** [comment]
wow.

**Comment by Agarian** [comment]
wow.

**Comment by firelightning13** [comment]
wow. got burn though

**Comment by LegitSoulja** [comment]
Somebody had an " ISSUE " with what I said. I don't know who said, but whoever said it fy. Come say it to my face.

You're actually wrong because if someone with that tone of language it's the opposite. I could care less for feelings if I'm disrespected. But you know what, 

Those people will eventually have things on there shoulder in the future for being the way they are. 

@firelightning nobody got "Burned" I'm pretty sure if I said something about this kid someone will complain "Which someone did". So you know, for me, I try to be a bigger person and not down myself, but with someone telling me to stfu I dare them to come say it personally too my face if they're tough enough. It doesn't matter what age. Apparently if you curse you're expected to be older than 18, so who's gonna get hit with the hot pan for being too young talking like a sailor? That kid.

And whoever is editing me comments don't touch my content again, or I won't never add anymore content and leave this place completely. With that being said for that person, you know who you are. Lucky I wasn't fast enough to catch you.

**Comment by LegitSoulja** [comment]
This place is sick, and going down really slow. Now I really see what Andrew means, and why he's closing it. I'm glad it will be, dealing with these types of kids, and non productive workers/Project leechers. (Nasty nasty bloody mess).

Someone really needs some soap and bleach for there mouth. I'd advice to gargle and swallow aswell.
