### ISSUE TITLE
 Spaces are braked very fast

### ISSUE THREAD

**Issue by RelTakeover** [AJS-development/Ogar-unlimited#1037]
"the brake of splits are very rigid"

the splits very rigid and the brake of splits is very fast

**Comment by firelightning13** [comment]
You mean physics problem?

**Comment by firelightning13** [comment]
I knew about this problem a long time ago. Apparently, Luka said it happens on normal agar.io. but for me, it's not really smooth. I think it's because:
It shouldn' move at all or move a little bit, or coast instead of brake that is very rigid

You can see how difference the physics between vanilla agar.io and ogar when you are about 200~500 mass when splitting or popped by virus

**Comment by RelTakeover** [comment]
i can change this ? where..

**Comment by raphyjb** [comment]
its in physics.. but it would be nice to have same splits as agar.io
I like better agar.io splits

**Comment by Megabyte918** [comment]
I'm trying to fix this, but its very difficult

**Comment by RelTakeover** [comment]
ok bro thanks
