### ISSUE TITLE
BLINKING BLOBS

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#1072]
These fudging blobs are blinking im having a seizure

**Comment by PrinceDark9243** [comment]
Do you have a gif so we can see what is the problem!

**Comment by LegitSoulja** [comment]
@PrinceDark9243 I think I know what he's talking about cause I had that problem and it was a browser problem. The problem was with chrome. After reinstalled it was fixed. But I don't use chrome specificity anymore since I found a replacement with less memory usage. It's still chrome, but better :).

###### Similiar Issues
* Blinking / Flashing cells
* Disappearing & Reappearing cell (normally when there's more than one cell other than mines in my view)

Was all fixed with a reinstall, I've had no more problems after that & have not experienced that again.i thought my graphics card was shot or something but gladly it wasn't. Hope it helps.
