### ISSUE TITLE
Bug or Glitch?

### ISSUE THREAD

**Issue by PrinceDark9243** [AJS-development/Ogar-unlimited#1100]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?
FFA
What version are you on?
17.3.1
What command did you type if any?
None
You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

Des:When i eject Mass at Corner its just pause my game and when i type in console it does not display my text it is a bug or Glitch?

**Comment by LegitSoulja** [comment]
When you shoot w's it lag worser than before. GG if it happens. The game doesn't pause, but it overloads and wait till whatever processes finish. **Which takes a long time**

This still happens whilst using jxcore :/. No help what so ever. It's sad that I can run a game no problem, but not ogarul.

I guess I'll just continue modding gta v :/. Nodejs and JavaScript is the worst languages but people have to deal with it. Thanks Netscape. I'll stick to C/C++ :U

**Comment by Andrews54757** [comment]
the lag is driving me crazy. WHAT THE F IS THE SOURCE OF IT!!!

**Comment by Andrews54757** [comment]
this is where we need @MichaelLeeHobbs . He is good at this stuff

**Comment by Andrews54757** [comment]
but he kinda disappeared :(

**Comment by Agarian** [comment]
Hes been inactive for the longest time

**Comment by David1ali12** [comment]
lag happens when big cells are W ing my server holds alot of players lag only happens when big cell are W ing

**Comment by Andrews54757** [comment]
I wish we had more EXPERIENCED programmers like @MichaelLeeHobbs or @LegitSoulja. But we don't .

**Comment by Megabyte918** [comment]
RIP Hobbs :(

**Comment by LegitSoulja** [comment]
Too make things clear, as of what I was told, he been known about agario till his kids showed him about it and he had helped his kids make a server and what not and was part of AJS. 

I don't think he was never intended to forever be part. Forgive me if I'm wrong or incorrect of what I said but that what it seemed like. 

Last time I ever spoke with him he had to take his kids to the doctor. I hope him and his kids are alright. I know i remember he posted on an issue before he took his kids some I'm hoping he's okay.

@Andrews54757 I can help, but I wouldn't want to be in the way. Personally I haven't been modifying ogarul nor nothing so I haven't been developing in ogarul except plugins. I have with Ogar until I found ogarul. I mean if you would like help I can help. Only if there was a todo list of some sort just so everybody is organized and up to date on a workspace. But idk dev's also need to manage a contact solution because we barely even have contact which is another downfall :/. But bare with me here. We all can work together and make ogarul better and efficient.
