### ISSUE TITLE
ouid Issue 

### ISSUE THREAD

**Issue by David1ali12** [AJS-development/Ogar-unlimited#1101]
the problem with ouid it gives all ogarul same ouid and thats make a big problem with statistics use 
it dont let  to list More than 1 server at the same time , please FIX it .
I used ssh it was pain to make all these folder  & take so much to figure out

**Comment by Andrews54757** [comment]
thats the entire point. 1 oiud for each machine. Ask @LegitSoulja so he can change it so you can have more than 1

**Comment by LegitSoulja** [comment]
@Andrews54757 Why do i have to do it? You made the ouid, you just need to change the file dir path of it being found and created instead of the directory **../../../ouid.txt**

Reason why: is because people don't have to make folders after folder for a specific ouid. This is bad for statistics because if a server is using the same ouid it just overwrites that one table with that id with both server's content instead of having a different unique ouid for each server, in each game directory. 

Like common. I run a  master folder on my desktop, im not expecting for an extra ouid.txt file on my desktop that'll probably end up getting deleting and then re-created again with a new ouid. 

It's even annoying to me, plus it will be complicating for other people who's using statistics. It's an optional fix but it just a problem for statistics.

**Comment by Andrews54757** [comment]
Quid is designed so it is unique for a machine, not for a server. This is for a good reason. I won't explain why.

**Comment by LegitSoulja** [comment]
@Andrews54757 well, I have a strict database, and I don't want alot of trash, so the only way for me to prevent that is from the server/machine uid. If i did it ip wise, people barely don't even know what they are doing, so they can make multiple different false tables in the database with invalid information.

My next step of approach of this is to strict statistics, meaning you will need to register and get a specific key for each server that's created per machine.
