### ISSUE TITLE
Virus Glitch

### ISSUE THREAD

**Issue by Soulened** [AJS-development/Ogar-unlimited#1141]
On the latest update to 17.3.6 a new glitch came. Sometimes when you try popsplit, the target just disappears and dies. This causes you to lose alot of mass. Popsplits do work sometimes, but so many times i saw a failed popsplit because of the glitch. Please fix this!

**Comment by Agarian** [comment]
Same here! I tried reporting it but it seems everyone ignores it.

**Comment by Agarian** [comment]
Mothercells can also dissapear

**Comment by Agarian** [comment]
This was my report : " For some reason, I'm seeing cells dissapear when they split a lot. For example: One time, I split my bot to 16 to feed me, BUT, 3 of my bot's cells dissapeared and my cell did too, which killed me. It's causing a lot of mass loss! I even tried splitting into a mothercell, instead of feeding the mothercell, it and 4 of my cells dissapeared! And after a while of entities dissapearing, LAG occurs. HELP!"
But apparently the other devs don't seem to give a shit.

**Comment by Agarian** [comment]
And still being ignored...

**Comment by Soulened** [comment]
:/ Hopefully they fix it soon

**Comment by Andrews54757** [comment]
Right now, Im working on other things, Il look into your issue next

**Comment by Agarian** [comment]
How can i lag with 3 players and 30 minions?

**Comment by XtremePlayzCODE** [comment]
good question

**Comment by Optimusprimeagario** [comment]
@Agarian  Because of the connections use a vps it will solve the problem and use nice one not cheap ones.

**Comment by Agarian** [comment]
Well its not like i can afford a VPS

**Comment by PrinceDark9243** [comment]
@Andrews54757 say it will be fixed in up coming update! in my issue

**Comment by LegitSoulja** [comment]
@Agarian save up money and build your owns like I did. I would never buy a vps neither.

**Comment by yohano** [comment]
Please Fix the Ultra bug! D:

**Comment by RepahidiS** [comment]
please fix this sh*t guys :D

**Comment by Megabyte918** [comment]
turn the ejected mass collision back on and try a virus throw

**Comment by Agarian** [comment]
This isn't about virus throws

**Comment by Agarian** [comment]
Should this be closed?

**Comment by Agarian** [comment]
And why does OgarUL have more issues than OgarProject?

**Comment by LegitSoulja** [comment]
Because of the kids that don't know what they are doing, and all the duplicate posts, and spam. All of that is like 30% of the issues. 

Looking at it kindof gives us bad reputation, but we can't help that unless we disable issues completely and move to the forums which I think we should do anyways.

**Comment by Megabyte918** [comment]
virus throws and dissapearing are fixed on my fork and will be merged later

**Comment by Agarian** [comment]
Wait virus throws??

**Comment by LegitSoulja** [comment]
How'd you fix virus throws? Isn't that kindof hard? Unless you stop virus split, and make split virus not collect any pellets within a few seconds before splitting again.
