### ISSUE TITLE
Why did you use Node.js

### ISSUE THREAD

**Issue by Soulened** [AJS-development/Ogar-unlimited#1150]
Why did you use node? Node only uses one core of your computer, so it lags *much* more. If it would use all the cores available, the servers wouldnt be as laggy and could keep more players without lag. 
You could have used #C or more complicated C. It would fix lag mostly and depending on a computer it would get 4x or 8x better running speed. Please convert them to some *GOOD* language other that node or javascript!

**Comment by LegitSoulja** [comment]
Because we didn't make Ogar!. Don't come to us with this. How would it be compatible if it wasn't nodejs and websocket to work with agario client. Go complain to miniclip about this, not us. We are just working with the flow. I do agree JavaScript is the worst & slowest bad performance language. I wished it was c language, or something else. I'd be more comfortable
