### ISSUE TITLE
Version 17.0.3 want back !!

### ISSUE THREAD

**Issue by zKurama** [AJS-development/Ogar-unlimited#1165]
The Last version is much lag, and very slowly, I want the version that works skins, has no lag, no lag with bot, version 17.0.3

**Comment by AgarioIsBest1602** [comment]
You can change the server version in index.ini. Almost on the top if you use notepad or sublime text

**Comment by Agarian** [comment]
Bruh not even gonna help

**Comment by raphyjb** [comment]
wut? u cant change version how?? were is the it situated /Ogar-unlimited/src/????

**Comment by Megabyte918** [comment]
@AgarioIsBest1602 @raphyjb you cant change the version like that, all it does is change the number and nothing else. And you can't get version 17.0.3 back because its not in the releases or anywhere else. Try using an older version in the releases idk
**p.s.** anyone got skype? im bored and i want to team with someone =P

**Comment by raphyjb** [comment]
I got skype: raphy.jb
(: But cant play today cuz im going somewere

**Comment by LegitSoulja** [comment]
OgarUnlimitedC will have a version changer :).
