### ISSUE TITLE
[suggestion] ZOOM FAR OUT

### ISSUE THREAD

**Issue by AgarioIsBest1602** [AJS-development/Ogar-unlimited#1168]
When im teaming with my bots and i have playerbots, i want my bot to split to a playerbot but it cant because i cant zoom out farther. This is just really annoying so i got the suggestion to add something so you can zoom out so much as u want.

COPYING THIS IS BEING BANNED FOR 1 MONTH!

**Comment by LegitSoulja** [comment]
Zoom out? Or render distance

**Comment by AgarioIsBest1602** [comment]
Zoom out. I was reading i can change the render distance but i dont know how to change the zoom

**Comment by Megabyte918** [comment]
It is impossible to add this if you want to use the official agario client because it doesn't support it, and it cannot be added onto play.ogarul.tk/ogarul.io because that would be cheating, everyone would use the maximum view distance and be able to see everyone on the map. Besides, why would you want to see the whole map anyway? it takes the fun out of the game, part of the fun is not being able to see whats coming up, big people have a advantage with a bigger view distance, smaller people have a smaller one. if this was added everyone would use/have the same view distance and whats the fun in that?

**Comment by AgarioIsBest1602** [comment]
I dont have to see the map but i just want i can zoom out so i can aim for my bot to split

**Comment by AgarioIsBest1602** [comment]
And i just want it to my own server

**Comment by Megabyte918** [comment]
@AgarioIsBest1602 im not exactly sure about this... but if your using your own custom client, or the updated client that Andrew has provided, the code for it might be in either of these 2 functions in main_out.js:
![capture](https://cloud.githubusercontent.com/assets/17245196/16450653/2bed94a6-3dcc-11e6-8985-600d185e0aaf.png)
try editing these and see what you get

**Comment by AgarioIsBest1602** [comment]
@Megabyte918 I cant find main_out.js

**Comment by Megabyte918** [comment]
https://github.com/AJS-development/Ogar-unlimited/issues/918#issuecomment-225019348
it should be in there
