### ISSUE TITLE
Im Making A Diep.io clone in PJS, are you gonna try to make one in node?

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1193]
THIS IS NOT AN ISSUE, I WAT DEVS TO SEE THIS

**Comment by LegitSoulja** [comment]
Um no. If it was a next thing it would be slither. 

Diep.io is alot of work to work with, also not enough people as a dev here. So limited development time. For me, im trying to take a break, and on the other hand im also working on projects.

OgarUnlimited still needs alot of work put into it, but im still kind of new here, and i really don't know the layout as much because im 4 or 5 months into node. So learning about game development on nodejs side is a new thing to me, that I still haven't looked over yet :/. I'm more into C language, and learning two languages at once when you only use one main language, the other languages you know will die out and you'll kind-of forget. I learned java around 2006, and I never had a use except when I used to play MC. I did development for plugins for servers, and mods aswell. Then I got more into doing C language when I was introduced . So i will be more into that then never, but im gonna switch over and take a look at how nodejs works because its kind-of interesting :).

**Comment by Agarian** [comment]
my computer cannot handle slither :P

**Comment by SharkFinPro** [comment]
Ok
+Agarian: :D

**Comment by SharkFinPro** [comment]
please close this now
