### ISSUE TITLE
Skins have correct name, but skin does not show up

### ISSUE THREAD

**Issue by XtremePlayzCODE** [AJS-development/Ogar-unlimited#1209]
sometimes when people have a skin, the skin does not show up and it is just the player color even though the skin name was spelled correctly. also happens with skin changer.

i think what the problem is for the skin changer are some names arent spelled correctly in randomskins.txt

**Comment by Tokoagar** [comment]
What skin changer?

**Comment by LegitSoulja** [comment]
I recently made changes to the skin layout. 

I have not checked to see if it was an issue because I didn't clear my recent cache, so there could be a few skins that's not working.

All the skins are listed here, http://play.ogarul.tk/skinlist.pho

Note that, the skin list is live, and any new skins added will be shown on the list aswell.

**Comment by XtremePlayzCODE** [comment]
I think replacing everything in randomskins.txt should be replaced with play.ogarul.tk/skinlist.php then. Maybe that would fix some of the bugs.

**Comment by AgarBeastZz** [comment]
still not working

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE umm.. xD then there wouldn't be no skins.. I would replace the random skins with the skinlist link with the skins that already exist.

**Comment by LegitSoulja** [comment]
@XtremePlayzCODE I figured out that, hotlinking was disabled for other clients to use the skins aswell, but this issue doesn't go towards play.ogarul.tk which the skins are hosting there, and is working as of right now.

For other clients, the skin directory is open for public use of using, and should now be viewed from other sites instead of just play.ogarul.tk

**Comment by LegitSoulja** [comment]
###### The skins that don't exist as of right now are these skins
```
alien
army
astronaut
blackcar
boot
breakfast
carro
chocoegg
coyote
glotpot
nose
panda
pizza
rainbow
shuttle
snake
space_dog
spider
statue
sumo
t_rex = **t-rex**
tigerpattern
ufo
venus
wasp
zebra
```

**Comment by AgarBeastZz** [comment]
?\

**Comment by AgarBeastZz** [comment]
ok

**Comment by Agarian** [comment]
lol blackcar is not a skin...

**Comment by Agarian** [comment]
i can link you to some of those

**Comment by LegitSoulja** [comment]
@Agarian I just pulled the skins from randomskins, and compared them both, and those was the skins that's not in the directory, or is spelled incorrectly.

Also check gitter, I have sometime to tell you that you should NOT share with others it will be removed permanently if leaked :/

**Comment by Agarian** [comment]
um k

**Comment by XtremePlayzCODE** [comment]
hmm...i think something fishy is going on.
YOU GOTTA TELL AGARIAN...



that his toast has been done for a while.

**Comment by Agarian** [comment]
@XtremePlayzCODE no.

**Comment by XtremePlayzCODE** [comment]
kk... you gotta tell agarian his... eggs... are... milked? idk

**Comment by LegitSoulja** [comment]
Looks like skins has been fixed, and also allowed for public client uses.
