### ISSUE TITLE
Is hamachi ever gonna be joinable-trough the server?

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#121]
Is hamachi ever gonna be joinable-trough the server?

**Comment by Megabyte918** [comment]
Hamachi already IS joinable through the server you just have to set it up the right way. However their IS a way to do it without hamachi but im not sure if it works for everybody

**Comment by Agarian** [comment]
portforward? that wont work 4 me

**Comment by Agarian** [comment]
how exactly should i set up hamachi for some1 to join my server?

**Comment by Megabyte918** [comment]
Okay I'm gonna show you 2 ways you can do this


The Hamachi method:

1: Make an Hamachi account at https://secure.logmein.com/products/hamachi/
2: download and install Hamachi (unmanaged or managed doesn't matter)
3: look up your ip address on google and port forward it
4: Open Hamachi and select "create a new network" and create one
5: tell the person you want to join to download and install Hamachi too and to join the same network your on
NOTE: The person you want to join MUST have Hamachi installed and must be connected to your network or else it wont work. If it doesn't work otherwise undo step 3 and try again.


 The Non-Hamachi method:

1: Look up your ip address on google and port forward it
2: Download and install uTorrent http://ll.www.utorrent.com/intl/en/
3: Once utorrent is installed, go to Options> Preferences> Connections> and set the port to whatever port your server is running on
4: restart utorrent
NOTE: step one must come before ANYTHING else or else it wont work. In order to keep your server public to anyone who wants to join, you must ALWAYS have utorrent running in the background while your server is running or else it will be unjoinable to anyone outside your wifi. Don't ask me why or how this works but it does xD

To connect yourself you have to enter agar.io/?ip=127.0.0.1:[serverport]
For other people to connect they have to enter agar.io/?ip=[your ip from google]:[serverport]

**Comment by Agarian** [comment]
Neither of those will work 4 me as i cannot portforward

**Comment by Megabyte918** [comment]
What can't you?

**Comment by Andrews54757** [comment]
For hamachi, you shouldn't need to port forward.

**Comment by Andrews54757** [comment]
because it "establishes a connection over the Internet that emulates the connection that would exist if the computers were connected over a local area network." quoting wikipedia.

**Comment by ErikParacelsus** [comment]
Don't use hamachi it will destroys your adapter.

**Comment by Agarian** [comment]
@ErikParacelsus how

**Comment by LegitSoulja** [comment]
@ErikParacelsus Network adapters cannot be destroyed. A simple restart would bring your default adapters back. Hamachi on the other hand I think creates a bridge connection, so it does no interfere with neither ethernet nor wifi adapters.

**Comment by Souf123** [comment]
why you guys not make a tutorial
