### ISSUE TITLE
Lag.

### ISSUE THREAD

**Issue by WolfOGG** [AJS-development/Ogar-unlimited#1254]
Is there a way I can fix lag myself, I recently noticed that when I add 20+ minions the server tends to lag bad, is there any possible way I can fix this?, I also noticed a different version of OgarUL called MultiOgar, they claim that by changing the term mass into score of a player the lag reduces which indeed is true, but he will not add plugins as well as minions :|

**Comment by MastaCoder** [comment]
no, Ogar-Unlimited will probably no way get near the performance of MultiOgar. All these extra, random features found in Ogar-Unlimited are not in MultiOgar, thus removing as much lag as possible.

**Comment by WolfOGG** [comment]
Is there any way to get a MultiOgar listed on the servers list like with OgarUL?

**Comment by LegitSoulja** [comment]
@WolfOGG I blocked all other servers other than OgarUnlimited!. Only OgarUnlimited servers are allowed. Not multiogar!.

http://stats.ogarul.tk/ban/

**Comment by LegitSoulja** [comment]
@WolfOGG OgarUnlimited is the owner of minions. If it wasn't for OgarUnlimited minions wouldn't exist. MultiOgar just can't steal the minion idea, plus it isn't supported / wrote to handle plugins, since OgarUnlimited was entirely re-coded, so the layout is different!.

I heard using this npm called **pm2** can be used to fix lag issues. I have no tried it but be my guest.

**Comment by MastaCoder** [comment]
@LegitSoulja Have you even went through the MultiOgar code? @Barbosik put a lot of work into making it as stable and performance wise as he can. I was playing on a 3000 x 3000 size map in experimental with 3 friends and OgarUnlimited was lagging every 4 seconds. How is this the same as Ogar? MultiOgar has more features such as admin optimization and many more in the work. We aren't just adding useless features that are just going to add on to the server load for no reason. Ogar-Unlimited is for kids to host their servers are home, it is in no way ready for an active, giant public, 24/7 server. MultiOgar is made for things like that, just the fact that it supports multiple protocols shows that.

pm2 will not fix lag unless if you guys do something to optimize your code and program. @WolfOGG we have our own server tracker and work with the mivabe tracker and our own, who needs Ogar-Unlimited? 

btw, you guys were technically the first server to support minions, but doesn't mean now no other server can get minions with them. That would pretty much mean you don't know what your license means. You are also forced to follow Ogar's license, remember that DMCA request a while ago? Players can simply download bot plugins and work them with Agar.io or their own client. I don't see what the real need is on the server side without access to extra keys.

**Comment by LegitSoulja** [comment]
Lol im not here to argue. I just said what I said, and I meant what I said. I have no comment to what you said. 

Just because you might not can handle OgarUl doesn't mean nobody else can. Before OgarUnlimited went into a big update, it was so popular that yes it COULD support alot of people. From then, to now alot of things have changed, so you can't even come here and argue. 

Even agariohub.net used ogarunlimited. I don't know about now but im pretty sure he is using an older version of ogarunlimited because he was the person who introduced me to this. 

We aren't forced to follow Ogar's license, yet this project is followed ogars license, but can be flipped over and created entirely a new way with our own license so don't even go there. Minions was brought in without the need of kiddies bot scripts and such. I guess you don't understand the name of OgarUnlimited and the reason why it was ever started. 

Of course it hasn't been optimized. Too be honest with you, this is still like a development stages of OgarUnlimited as of now until a stable version. If I was here way earlier, stable would still be v11.9.0 which is the original branch, until new things was added, and tested before merged, but OgarUnlimited been so off track, you can't complain of all the hard work andrew has been doing. You can't even compare us to nothing until a stable. Just wait.. There's gonna be so much to this in the future you won't be able to say nothing.

**Comment by MastaCoder** [comment]
Used it just a week ago and was lagging, got a couple hundred commits since then because all the commits are just all over the place, but that's okay we can see some progress. I'm pretty sure it's not my computer or my server. This was running on x2 Intel Xeon E5 whatever the hell they are clocked at 2.3Ghz on 8 cores. CPU usage was under 25% that whole time it was running with less than 1gb of ram under use.

Good thing you brought up agariohub.net! I've known the owner of the website since his launch. (Biel) In the first times that he owned his website he was using Ogar that was extremely optimized and changed to match the physics that he had made up with the entities that he made. We worked together, I gave him ideas for his website and he assisted me with finding issues on mine. He was the person to solve the virus split issue before anyone on Ogar could, how the virus mass was supposed to be added before the split to have same size pieces and we were pretty much the only people that had it at the time. Later on I introduced him to OgarServ and he built his server upon that because of the lag fixes and how optimized the server is. He was in search for the skin protocol at the time and was playing with a bunch of tweaks and such but couldn't find them. Ogar-Unlimited came out with skins at the time and I sent him it, he took your skin protocol and built it into his server. So his server is not even close to being built on OgarUnlimited, plus, haven't you noticed how his bigger server lag? hm?

Ogar-Unlimited got a DMCA request not 2 months ago with all other Ogar clones (OgarServ) about switching the license. Ask @Andrews54757 himself, make sure to read the Apache2 license yourself if you can, section 4, part C explicitly states: "You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works...", pretty sure you have to keep the license the same under those terms as many parts of your code is still based off Ogar's, and you know as a fact it is built off Ogar so don't even try to find loopholes.

**Comment by David1ali12** [comment]
Soon Ogarul will be clean up with Fast performance and get a new stable version :) 
the reason of lag is Ogarul uses Too many node Module in my option 
stable version 11.9.0 of Ogarul has Great performance tho

**Comment by LegitSoulja** [comment]
I was going to write OgarUnlimited in c# but nobody here knows c# and that would be so much work to do. If I would've customly wrote OgarUnlimited c# then no it would not be against that license at all since I custom wrote it, and not directly from Ogar's source. 

Yes, me myself worked with bielssa. He helped me, I helped him at times. We are still good contacts. That what made me create agariohub.tk which was similar but since I don't no longer host servers I shut the site down because I was developing a new game and have another use for my services I own that I have built. 

But yea. I do agree with you OgarUnlimited needs a lot of optimizations. That's all it really needs for better performance, but a lot of just thrown together that I've noticed. Hopefully one of these days OgarUnlimited will be re-wrote again better than it is now.

**Comment by Andrews54757** [comment]
@MastaCoder I am overly impressed with multiogar. I am still kinda new to nodejs, so that is probably why it is thrown all over the place. Remember, I didn't learn Node by taking classes. the OgarUL project is a learning experience for me. In the future, Im gonna settle with objective c and such. This is because my long term project will be a browser called Fetch. OgarUl is an experiment for me, and I hope MultiOgar does get much farther than OgarUl, It would be interesting to see the progress they made. @MichaelLeeHobbs used to deal with the lag, but he is now busy and I understand that. I also feel bad for Barbosk. now he will have to deal with useless issues with children begging for something. Overall, this is a short term project. It is to exercise my brain for a bigger one. Also know that I am still pretty young, so there are still other dreams I want to fulfill. My main trait is Innovation. I love to innovate, and I feel like the world really needs innovators. Maybe in the future you will notice me. Now, I am slowly not supporting ogarUL as I am learning how to create browsers and such.

**Comment by LegitSoulja** [comment]
Why objective C though? I mean that's good that you will possibly make a browser better than safari, but you could also accomplish making an even better browser C language wise.

Nice thought though, but what new additions to the browser will you be adding? Instead of what most browsers already have, which is mainly going towards new JavaScript e6 right? And WebKit .

**Comment by Barbosik** [comment]
Actually I started MultiOgar just to revive private servers after protocol update. And it's my first project in javascript :) I never had to deal with node.js before.
First I just suggested some solutions to Ogar project. But it was implemented in the wrong way, so I started MultiOgar and implemented multi protocol support. After that I found that Ogar code has a lot of garbage and make a little cleanup. I was impressed with node.js performance and started to learn how to optimize it. MultiOgar gives the main performance gain from using binary tree for fast search. Also it has protocol optimizations to reduce network traffic which also gives significant performance gain.

**Comment by Agarian** [comment]
Which explains why it ran so well even in a 1 core 1GB environment

**Comment by Barbosik** [comment]
latest version allows to run 2-3 servers on 1 GB machine with 30-40 players on each server :)

**Comment by Agarian** [comment]
Shit dude, we could use your expertise here!

**Comment by MastaCoder** [comment]
@Andrews54757 I totally understand all of that, the work you put in is good and should be continued as you simply learn from all of this being done. I didn't want to bash this project, rather show some flaws and compare it to other projects. Maybe with that information you can work on learning and improving it more. It's how things get better :+1:

**Comment by Andrews54757** [comment]
It would be nice to have @Barbosik here, but he is probably busy with multiogar, and he probably doesnt want to start from square one again

**Comment by Barbosik** [comment]
@Andrews54757: I like a small and fast code with minimum functionality and maximum flexibility. Ogar Unlimited using very large and complicated code for me. I even want to cut off half of the code in MultiOgar...
