### ISSUE TITLE
Ban This IP: 90.208.2.189

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1299]
Using Software To Spam The Chat

**Comment by NatsuTheGreat** [comment]
Did it spam from multiple nulls or from this specific IP?

**Comment by Agarian** [comment]
Hemp may have connected to the server multiple times at once then spammed it from there idk

**Comment by NatsuTheGreat** [comment]
Well I need more details from SharkFin

**Comment by LegitSoulja** [comment]
@SharkFinPro I told you, if anyone gets banned from the site, you need to provide details about the situation. If he is somehow using a spam bot, I guess ill add a spam limiter to the chat client side aswell instead of depending on the server to handle the spam.

**Comment by SharkFinPro** [comment]
I Said: They Were Using Spamming Software.

New Info:
It was just that ip
I forgot what the software was :|

**Comment by firelightning13** [comment]
Using keyboard macro i guess

**Comment by LegitSoulja** [comment]
@firelightning13 there's a difference between site ban, and server banning. 1 spoil apple, can spoil every last other server, so site banning is a thing. 

@SharkFinPro You wouldn't know what software tool he was using, unless the tool said the name of the tool with the spammed text. You need to provide evidence, and the evidence of the ip of that person. You can possibly get an ip wrong, so site banning is really strict. Just because you say ban this ip I wont ban that ip without given evidence. Therefor this person will not get banned.

**Comment by SharkFinPro** [comment]
it said the name

**Comment by SharkFinPro** [comment]
i saved it in my browsers history :D

**Comment by SharkFinPro** [comment]
here is the link:
http://deluxe-tools.net/tools/chatspam

**Comment by LegitSoulja** [comment]
@SharkFinPro You still didn't provide evidence, you just gave me a link to some tools which doesn't give me proof of this crime. I removed the link. Therefor this issue will be locked.
