### ISSUE TITLE
using agar mods

### ISSUE THREAD

**Issue by problemsofworld** [AJS-development/Ogar-unlimited#130]
I can't use agarmods it give the game sound and make more fun . is there's a way that I can use it ?

**Comment by Megabyte918** [comment]
Unfortunately, there is not at the moment :( 
Ever since agar.io's latest update, they rendered most botting extensions useless, and same with AgarioMods. As of now you can no longer use agariomods in private servers or public servers. I hope they fix this soon cause I agree, it did make it more fun :)

**Comment by Agarian** [comment]
i thought i could close issues since i was a member of this lol

**Comment by Megabyte918** [comment]
Hahaha
