### ISSUE TITLE
chatban code error & special character error

### ISSUE THREAD

**Issue by bigstery** [AJS-development/Ogar-unlimited#1310]
<a href="http://hizliresim.com/DJ0zWl"><img src="http://i.hizliresim.com/DJ0zWl.png"></a>

<a href="http://hizliresim.com/J2yRoQ"><img src="http://i.hizliresim.com/J2yRoQ.png"></a>

1-countdown does not write flood
2-As seen in the picture. chat ban gives error code.
3-〖ƔŤṦ〗קєǤᗩᔕᑌᔕ < Such nicks do not appear in the list of players. names ???? as it seems.
4- very difficult to ban players who entered the names with special characters

**Comment by Tokoagar** [comment]
It's normal the console can't see the symbol Im not sure they can fix it

**Comment by NatsuTheGreat** [comment]
Usually consoles cannot read all uni-code characters thus you will get ???? or some other replacing character.

**Comment by Megabyte918** [comment]
Man, it'd be great if the chatban error pointed to a specific location -.-

**Comment by LegitSoulja** [comment]
@Megabyte918 nothing isn't wrong with chatban, it's the pm of chat sending. Obviously if you learn how to read a stacktrace, console was logged before the crash. The only event there that can cause the issue is gameServer.pm which I proved was broken from the start. You can chat all, but not pm, well atleast, not for running pm as a command, nor using gameServer.pm

**Comment by LegitSoulja** [comment]
@NatsuTheGreat it's possible to output unicode in console, but I don't know about nodejs, but i know for a fact I can print out unicode using c#. Maybe there's a certain way to print it in console, instead of making it a string then logging it :/
