### ISSUE TITLE
Can someone create a client that actually works properly?

### ISSUE THREAD

**Issue by darknight99x** [AJS-development/Ogar-unlimited#1311]
Hi, the clients I have been seeing floating around are just god damn awful.

They are VERY laggy and the mouse stops responding to the entire webpage, and requires a refresh.

Can someone code a client properly or fix the lag on the current ones? It's unbearably bad.

**Comment by mrzack506** [comment]
Also, if you were to put in a custom ip (ex: function connectToServer() {
var defaultserv = "ws://(IP)" ) the page would only load on chrome EVEN if it has the mobile fix. 
This is a problem as players can only play on chrome or opera, not mozilla etc. They also can't play on mobile in general.

**Comment by Agarian** [comment]
I have that mouse bug aswell. @LegitSoulja see? Im not the only one experiencing that bug.

**Comment by LegitSoulja** [comment]
@Agarian Talk to andrew about the client. I barely don't know much about client api because if i did i would re-write it better. No we didn't make the client, whoever made it wrote it badly, and I do agree.

@mrzack506 there was never no mobile fix. The mobile fix was mainly for having the client properly playable from mobile with the appropriate canvas size for mobile screens. I only use chrome(canary) and have not use any other browser. I have used firefox, and opera in the past and in fact they do work from what I have seen. I really don't play much, so im not like a daily person who get those experiences.

I work now, full time every week, so i may not no longer be active unless on the weekends cause i come home and go to sleep, the right back to work again, so I barely even have time to do anything like I used to. But, idk what to say about the client and what to do about it right now unless andrew decides to make it better, because depending on me to fix the client is out of luck.

@Andrews54757 You told me a while ago about you no longer having access to the site(files). I responded, but it never looks like I get a response from you. Please let me know asap. Thanks.

**Comment by Agarian** [comment]
Closing for now then

**Comment by Agarian** [comment]
But is the mouse bug fixable?

**Comment by LegitSoulja** [comment]
I haven't added a canvas focus yet because I haven't got a chance to. I'm off work, and for this weekend. I'll finally take a look at it tomorrow morning jgez

**Comment by LegitSoulja** [comment]
That's the only fix I can think of that work, or either it's the script that just breaks completely after a certain amount of time.

I'll try to clean the client up a bit, and fix it, and I'll look more into canvas API and add a few additional things.
