### ISSUE TITLE
I just have 2 problems !

### ISSUE THREAD

**Issue by DarkZYT** [AJS-development/Ogar-unlimited#1324]
********************************************************************************************************************************
Problem 1 : i portforwarded all ports , server is added to stats list , everyone can join , but people laaag sooo hard , i tried to make the amount of minions and bots smaller , nothing happens , i tried to remove bots , nothing happens , ps : i host from my pc , can someone help me ?
********************************************************************************************************************************
Problem 2 : sometimes when i popsplit a bot or someone , some cells disappear , whyyyyy  ????
********************************************************************************************************************************
<center><h1>                                                   THANKS!

**Comment by NatsuTheGreat** [comment]
Issue 1:
Try restarting you router. This is probably your internet causing the massive lag.
Issue 2: I believe it's because of an incorrectly placed ```setTimeout``` or ```setInterval``` can't recall which commit has this issue.

**Comment by Agarian** [comment]
@NatsuTheGreat https://github.com/AJS-development/Ogar-unlimited/pull/1124

**Comment by DarkZYT** [comment]
i tried a lot of times restarting the router maybe i should change the port ?

**Comment by LegitSoulja** [comment]
Does your router has an option to reset packets? Sometime router don't dump those things. Home routers are the worst router for hosting things because they never handle packages, like how server router manages that.

With my router, if messages concerned as spam they get dropped instantly, and pretty much makes connections more faster than usual. Also, within a limit of packages, they aswell get dropped instead of my router being flooded. Note that your router also have a CPU, and memory bandwidth and it's not a lot for normal home routers can hold. 

If your router is basic, look up DD-WRT. They may can help you. Note that if you don't have experience with routers, and router updates I would recommend not using this because you'll be stuck without internet till you figure out your right settings. Just make a backup before doing so :/.

**Comment by DarkZYT** [comment]
Thanks!
