### ISSUE TITLE
Recently DDoSed (or threatened)

### ISSUE THREAD

**Issue by wassupmyagarios** [AJS-development/Ogar-unlimited#1348]
Hello, I am the owner of Torto public server and I was recently DDosed. Someone came onto my server and posted their twitter saying they were DDosing. I then shut down my server and experienced tons of lag on my network. I do understand this might not be an appropriate place to post this, but I believed this was very serious. So if this was an inappropriate place to post, please just close this. I do not have an issue but, would like to warn **everyone**.

Thanks, -Torto

**Comment by LegitSoulja** [comment]
@wassupmyagarios Hey, Sorry about your issue. You should try to get DNS security on your ip so that this would less likely to happen. Any body at some point who has the power to do a denial attack will most likely use it for force. I'd hate to see people in the community of ogarul using these types tools. Really, it's pointless for people to do this, but mainly the people who does these types of things really don't have no life whatso ever. 

Try to get security on your ip, or see if your hosting provider has some type of secruity with denial of service attacks. Hope to see your server back public again.. If you ever witness people that use denial of service attacks please let me know so that I can deal with them for not being able to access no ogarul content.

**Comment by systemroot** [comment]
not just this. but try to write 
**`lastb`** if you are running linux. at my srv was more than 600 fail logins. 
You will need to secure your server before to make it public.

**Comment by fayizan** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/19163419/17078485/10203946-5112-11e6-96ef-ba7b1035d3e2.jpg)

I deleted my linux vps tho

**Comment by systemroot** [comment]
@fayizan  use fail2ban with iptables `3 fail = banip`

**Comment by fayizan** [comment]
@systemroot Thank you

**Comment by wassupmyagarios** [comment]
@LegitSoulija I decided just to change my name to Vortex for safety, my server is still online and if I could get a ogarul.tk domain that would be great. I don't know if I will change my name back soon, but the attack didn't cause any harm. Thanks for commenting!

**Comment by LegitSoulja** [comment]
@wassupmyagarios
What's the IP that you use for your servers?

**Comment by wassupmyagarios** [comment]
@LegitSoulja 98.236.80.75

**Comment by NatsuTheGreat** [comment]
Not a good idea to put that here, anyone can DDoS it.

**Comment by Agarian** [comment]
I'm removing it

**Comment by fayizan** [comment]
how to DDOS..?? I m interested LoL

**Comment by LegitSoulja** [comment]
Well, bump. I wasn't able to catch it before it got removed. Well sorry, but I can't give you a custom domain part of ogarul.tk for your server.

**Comment by LegitSoulja** [comment]
@wassupmyagarios

Just email me, support@legitsoulja.info

I'll accept it from there.

**Comment by NatsuTheGreat** [comment]
@fayizan I hope you like getting into police custody too. How could you even ask that? Even as a joke?

**Comment by fayizan** [comment]
@NatsuTheGreat I was just kidding..

**Comment by NatsuTheGreat** [comment]
>Even as a joke?

**Comment by fayizan** [comment]
lol I don't know DDOS and I m not going to do it anyway, I said bcoz to troll @wassupmyagarios 
Don't Worry :+1:
