### ISSUE TITLE
Could Someone Please Finish up the ip bots

### ISSUE THREAD

**Issue by fayizan** [AJS-development/Ogar-unlimited#1357]
I m really need it bcoz I m tired of adding bots each time the player ID resets and Server Restarts and to feed the servers,Please Someone help me

**Comment by LegitSoulja** [comment]
@fayizan I got you before I go. Ill pass it to you here, and also on skype when im done. I don't think Ill even be able to make the shops where people can buy bots for the server.

**Comment by LegitSoulja** [comment]
@fayizan 
[ipbots.zip](https://github.com/AJS-development/Ogar-unlimited/files/382859/ipbots.zip)

###### Commands
* ```ipbot add [id or ip] [minion amount]``` (Using ID will fetch the ip address instead of you having to type it)
* ```ipbot rem [id or ip]``` (If ID is in game, you can use this to get a player ip address, other than that its the opposite)
* ```ipbot help``` (Displays help)
* ```ipbot cache``` (Displays current bot list)
* ```ipbot getip [id]``` (Gets player IP from ID **Just something helpful**)
* ```ipbot getid [ip]``` (Get player ID from IP **Just something helpful**)

Bot list is stored in log.json which is randomly generated when the plugin starts. You are allowed to edit from there, but a restart of the server is required to take effect. Bot list (log.json) is updated every 30 seconds. For a player to get a bot, after there ip has been added they will have to re-join the server to obtain them. I have not added a timer for the bots yet, but this will be sometime added in the future, or by someone else.

If you ever happen to experience any bugs, since I really didn't test it email me. My email is found on my github page., or have a AJS member to look over it. I'm pretty sure andrew will re-write this better but, here it is now.

**Comment by fayizan** [comment]
Thank you so much @LegitSoulja,I will miss you soo much 
last request can u please skype me your Github email id as I cant find it

**Comment by LegitSoulja** [comment]
support@legitsoulja.info

**Comment by fayizan** [comment]
@LegitSoulja  Thank you once again legitsoulja... :+1:

**Comment by fayizan** [comment]
@LegitSoulja I sent u the logs of console to your email,please check it

**Comment by LegitSoulja** [comment]
@fayizan 
* Removed console (Checking player log) **I forgot**
* Fixed player removable, which was a typo

[ipbots.zip](https://github.com/AJS-development/Ogar-unlimited/files/383033/ipbots.zip)

**Comment by LegitSoulja** [comment]
Added new command functionality
* ipbot rem all

[ipbots.zip](https://github.com/AJS-development/Ogar-unlimited/files/383053/ipbots.zip)

**Comment by fayizan** [comment]
@LegitSoulja bots were not generating in game

**Comment by fayizan** [comment]
@LegitSoulja sorry its working but I have to restart my server

**Comment by LegitSoulja** [comment]
Yea.. Unfortunately :/. Only if plugins can be updated live without restarting. Which is possible, but I can't actually do that now since it's not part of the plugin library.

**Comment by LegitSoulja** [comment]
@fayizan Last update fix
[ipbots.zip](https://github.com/AJS-development/Ogar-unlimited/files/385057/ipbots.zip)

**Comment by LegitSoulja** [comment]
More Fixes
* Minions cannot mistakenly get minions.
* If a IP was removed, then re-added bots will not be added again since it has already been added.

> Next update should finally have a timer (limit) in which a player will have minions for.
[ipbots.zip](https://github.com/AJS-development/Ogar-unlimited/files/385402/ipbots.zip)

**Comment by fayizan** [comment]
@LegitSoulja Could uou please have the ipbot config to set minion starting mass like superminion bcoz players love to play with starting mass more than 200+ in ogarul.

**Comment by LegitSoulja** [comment]
@fayizan How about ipbots can only be used with superminions? Since i've never actually used it, But I heard that you can't set superminions mass lower than the actual player start mass, but you can make it larger.

**Comment by LegitSoulja** [comment]
Hurry with your final requests for ipbots because next week ill be gone. Which means, I will no longer be participated in github activates, include ogarul.

**Comment by Megabyte918** [comment]
@LegitSoulja How can I get the output of my commands from the OgarConsole terminal to stay in said terminal, rather than appearing in my c9 terminal? If I do something like "playerlist" it won't show up in the console page, the actual list of players would show up in my c9 terminal instead, basically making OgarConsole useless and unusable

**Comment by fayizan** [comment]
ohh I didn't know about superminion feature completely but it will be cool to set starting mass better the ipbots be like superminion :+1:

**Comment by LegitSoulja** [comment]
@fayizan Here's the superminion update. Change the config inside ipbot for your needs.
[ipbots.zip](https://github.com/AJS-development/Ogar-unlimited/files/386882/ipbots.zip)

@Megabyte918 ?? If you are using a playerlist, and if that player list is large to be send to and from sockets, it will take a longer time for that playerlist to show in the console. 

When you execute commands, its the same as executing them from the terminal, but ogarconsole is more like a remote. Use or or don't use it. It was never intended for ogarul use. I made OgarConsole due to me hosting ogar servers in the future, which allowed people to have access to there own console in cpanel. But since I never hosted, OgarConsole was a thing, and plus was also turned into a plugin for OgarConsole. Either you find the use for it or don't. If you have a terminal that you can ACCESS then don't use OgarConsole.

**Comment by Megabyte918** [comment]
@LegitSoulja Oh yeah... I see what you mean now it wasnt NOT displaying in the console I just wasn't waiting long enough for it to load. Thank you :D

**Comment by LegitSoulja** [comment]
@Megabyte918 Like I said before.. You can have that plugin, if you want. You can update it however you like. I was thinking about splitting the log by line break, and then send each line to the console instead of sending large amounts of data at once. Maybe you can make that change. It would be better, but i don't know how performance wise will go.

**Comment by fayizan** [comment]
@LegitSoulja thank you so much for the superminion feature.... :+1:  will you add time feature..??

**Comment by LegitSoulja** [comment]
Eventually...

**Comment by LegitSoulja** [comment]
Maybe after I'm finished moving

**Comment by LegitSoulja** [comment]
@fayizan https://github.com/AJS-development/Ogar-unlimited/issues/1373
