### ISSUE TITLE
Sudden lag from nowhere

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#1360]
Playing for 8min and all of sudden, innsane lagging like i had 4 fps

**Comment by SharkFinPro** [comment]
were you doing other stuff? streaming from youtube? or was the only thing running the console and the browser on play.ogarul.tk?

**Comment by UltraSirius** [comment]
@elitajmx some Server Are Lagging Are Because Of Their Specs. You know Node.js Only Has Single Thread? @Andrews54757 Is Creating Child Process To Reduce Lags. To Stop Lagging. Try To Stop Downloading. Close Anything And Get More Internet MBPS Speeds. <--- (Not Sure If MBPS Still Works) FPS Is Frame (For Example) FPS Is Used By Your PC (Not Internet I Mean) So If U have Low Specs. Get More Memorys And Processors Speed. (Also Defrag Your Disk And Scan For Viruses)

**Comment by elitajmx** [comment]
I was running the consoole and playin on ogarul, whats the prob
