### ISSUE TITLE
About the splitVersion config 

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1361]
I was thinking, how about if it is set to 0, it uses ogar's OLD/ORIGINAL splitting? And if 1, it uses OgarUL's splitting. Ogar's original splitting can be retrieved from https://github.com/OgarPlus/Ogar-Plus

**Comment by SharkFinPro** [comment]
wut...

**Comment by Barbosik** [comment]
@Agarian: https://github.com/OgarPlus/Ogar-Plus uses incorrect formula `30 * Math.pow(this.mass, -1.0 / 4.5)`, it will leads to higher speed for higher mass.

You can use this formula: https://github.com/Barbosik/MultiOgar/blob/master/src/entity/Cell.js#L84

It's approximated from old vanilla servers.

For comparison, speed value for cell size from 32 to 1500 (mass from 10 to 22500) with size step 50.
Red line - speed used in OgarPlus and OgarUnlimited;
Blue line - speed used in MultiOgar
![Speed comparison](http://i.imgur.com/ejxfU5y.png)

As you can see, OgarPlus and OgarUnlimited uses higher speed for higher mass.

**Comment by GhostShot3** [comment]
@Barbosik Good explanation.

**Comment by NatsuTheGreat** [comment]
It should be the other way around. Lmao.

**Comment by Agarian** [comment]
@Barbosik i realize that, i wanted to import Ogar's original splitting into the `splitVersion`
And i realize the mistake i made with the issue title

**Comment by Megabyte918** [comment]
Why would you want ogar's original splitting for?

**Comment by Agarian** [comment]
Just for the hell of it

**Comment by Agarian** [comment]
Nevermind, i figured it out

**Comment by Agarian** [comment]
@Megabyte918 You have time for discord or something?

**Comment by Megabyte918** [comment]
@Barbosik I tried using your formula, It did not work. 

This is assuming playerSpeed is 30, and this.mass is 1k:

**OgarUL's formula:** *30 * (1000 ^ -1 / 4.5) * 50 / 40 = -0.0083 per every 1k mass*
**MultiOgar's formula:** *2.1106 / 1000 ^ 0.449 * 40 * 30 = -114 per every 1k mass? wtf?*

I see things like:
`var speed = Math.min(this.getSpeed(), dist);`
`var splitSpeed = gameServer.config.splitSpeed + (split.getSpeed() * 3 / 2);`
in the OgarUL code however,

But I also see things like this:
<pre>d = Math.min(d, 32) / 32;
var speed = this.getSpeed() * d; </pre>`
In MultiOgar's code and you guys also use a speed multiplier (1 for normal speed, 2 for twice as fast, etc) instead of just the number 30.

**Comment by Barbosik** [comment]
@Megabyte918: it works, just run MultiOgar. OgarUL doesn't use Cell.getSpeed (or at least not always), it uses formula in another place.

You need to take into account, that MultiOgar using cell size instad of mass for speed calculation.
In your example, mass = 1000 is a size = 316,227766, so the speed for 1 millisecond step will be:
```
var speed = 2.1106 / Math.pow(316,227766, 0.449) = 2.1106 / 13,258671177 = 0,1591863899;
```
for 40 ms step (MultiOgar) it will be 40 * 0,1591863899 = 6,367455597
for 50 ms step (OgarUL/Ogar) it will be 50 * 0,1591863899 = 7,9593194963
