### ISSUE TITLE
Things That Ogar Unlimited Needs Update.

### ISSUE THREAD

**Issue by UltraSirius** [AJS-development/Ogar-unlimited#1364]
Its Oggy/Slark Again And Here We Know That Ogar Projects Are Really Great! But We Think We Need Are Extreme Improvements! (Because we known MINISHIT Has been takenover.) So I am requesting Again.

For @Andrews54757 @Megabyte918 @Agarian (I dont know If Agarian is An Creator Also In Ogar Unlimited)

1#: BOTS - We Know Players Love Playing Without real Players! But Bots! Other Bots Are Idiot You Know?
So We Must Request it: 
- Bots Can Ignore Viruses (Actually They Never do that -_-) 
- Bots will Do Technic ( Doing Popsplit,TrickSplit,CannonSplit, And Other technic) 
- Greatter Alerts. (This Will Alerts Bots When A real Player Will Split The BOT)(Acually It Will Ivade,Even It will split if a real player  do Cannonsplit)
- Ability To Shoot Viruses (Making them More Like A Human Playing System)(Make it real) 
- Ability To Team Others (This Will Make Them To Team With You Or Other BOTS)(Randoms Are Enemy randoms While Others Willl team),(AND MORE. how to team with them is eject a mass for 5x) (Then team)

2#: STRUCTURES - So Basically. Cells,Viruses And MapFloor Include Foods Are The Main Things For Agar.io, Lets Change Them. 

-  Improvement Of MapFloor (Adding A Minimap Where your position is.) 
- Changing the Structure Of cells And Virus (Like At The Agar.io, Cuz I WANT TO INSULT MONEYSHIT?)
- Add A arrow Indicator (Making a Guide where there Mouse is pointing Is)
- Adding A Split Indicator (This is a Guide Where nor Players Can Split it Or Not or Swallow It Only.) (Your Cell: Red - All Players Cansplit At U, Orange - Cant Split With u But Can Swallow u) (The Other Player Cell: - White: You can swallow him but cant Split, Green: You Can Split him As Possible) 
- Adding A Powerups Shop (No Buying SKINS!) For Poweups Only! Like Mass Boost And XP Boost And Coins BOOST!
- Adding A Coin,Level System (No Money!) If u eat A One Player You will gain 25+ coins! and 25+ XP (That we dont need to PAY! We Are Not Like MINIMONEYMOOSHIT!)

This Is my Suggeestion Where We Need Improvements for Ogar Unlimited

**Comment by fodse** [comment]
OH
MY
GOD

**Comment by firelightning13** [comment]
Andrew is the owner of OgarUL

**Comment by firelightning13** [comment]
> For @Andrews54757 @Megabyte918 @Agarian (I dont know If Agarian is An Creator Also In Ogar Unlimited)

Andrew is the owner

**Comment by Megabyte918** [comment]
@UltraSirius We don't need anything else extra with bots, they are (kinda) solo players for now. Ogarul is already laggy as it it, but all the calculations they would need to do to do all that stuff you described above would cause even more lag and it would require more resources to run said bots. Maybe in the future after Andrew's update or if he gets rid of the lag as he said, we might experiment with AI. But right now is just not a good time to do that. 

> Improvement Of MapFloor (Adding A Minimap Where your position is.)

If you want your own Minimap, use an extension with the vanilla client. Or find someone who might have an extension for play.ogarul.tk or might be able to make one, adding one to play.ogarul.tk itself wouldn't be fair to other players and would take the fun out of the game, as well as increase the possibility of bringing suicide bots back :/

> Changing the Structure Of cells And Virus (Like At The Agar.io, Cuz I WANT TO INSULT MONEYSHIT?)

What?? You could change the "structure" by changing the RGB colors in virus.js to something different or by changing the spiked configs so that it would be smooth. But thats about all I know.

> Add A arrow Indicator (Making a Guide where there Mouse is pointing Is)

Useless.

> Adding A Split Indicator (This is a Guide Where nor Players Can Split it Or Not or Swallow It Only.) (Your Cell: Red - All Players Cansplit At U, Orange - Cant Split With u But Can Swallow u) (The Other Player Cell: - White: You can swallow him but cant Split, Green: You Can Split him As Possible)

Read what I said above about minimap.

> Adding A Powerups Shop (No Buying SKINS!) For Poweups Only! Like Mass Boost And XP Boost And Coins BOOST!
Adding A Coin,Level System (No Money!) If u eat A One Player You will gain 25+ coins! and 25+ XP (That we dont need to PAY! We Are Not Like MINIMONEYMOOSHIT!)

I think @LegitSoulja was working on this at some point, unfortunately he had to leave, so this is no longer in development. I would try to add this If I knew how such a thing would be possible, but sadly I do not. Me and him tried to add the cell borders once like in vanilla, but the current play.ogarul.tk client is so horribly coded, and hard to read and understand how it works that we couldn't even do that simple thing :/ Ask some of the other devs or someone who has experience with working with clients if they know how to do it or if they could work on it, it is a good idea.

**Comment by multa2** [comment]
This guy wants it all ? really ? learn js
