### ISSUE TITLE
JiffyBox VPS [HELP]

### ISSUE THREAD

**Issue by MizzahHD** [AJS-development/Ogar-unlimited#1397]
I need some help! I've gotten myself a 24-Hour Trial VPS which is a JiffyBox VPS.
Now i do not know how to configure the Ogar Server with that VPS, and i really need some help.
How do you setup the OgarUL Server with a VPS?

**Comment by Megabyte918** [comment]
Nobody here knows what JiffyBox VPS is, nor has used it. So we do not know any more than you do about how to set it up on that. We do not help with hosting anyway, in order to setup a VPS you must have your own knowledge about it. And not to be rude, but why would you even get yourself that VPS if you knew nothing about it in the first place? If you can't manage to use a VPS just host your server on play.ogarul.tk instead, its much easier.
