### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by WolfOGG** [AJS-development/Ogar-unlimited#1409]
Why is it that when I click out of the browser for example, click on the cmd to enter a command or something the game stops lagging but when I click back in its lags again?

**Comment by bangana** [comment]
your pc is sh*t ?

**Comment by azizhammadi1** [comment]
give me the link of game


2016-08-12 16:54 GMT+02:00 bangana <notifications@github.com>:

**Comment by LegitSoulja** [comment]
@WolfOGG because, canvas don't run in background. Like for example if you open and go to another tab, or minimize your browser this will happen. When you return back, alot of things happens to catch up with time you didn't see. 

I don't think by using another window(cmd) whilst the tab is still shown on browser will cause for the game to stop. I never had this happen me..

**Comment by Megabyte918** [comment]
@LegitSoulja Can you fix this bug while your working on the client? And that cmd bug also happens to me sometimes, but very rarely.

**Comment by LegitSoulja** [comment]
@Megabyte918 that is something that cannot be fixed, but I can fix performance wise so things will load faster even if the client did not respond for a while. 

I've been working on making this new client for about 2 weeks now :/ . Really really tired.
