### ISSUE TITLE
What should we be expecting in the new client?

### ISSUE THREAD

**Issue by Hunter2890** [AJS-development/Ogar-unlimited#1412]
Okay so the new client that you are working on this is what i'm thinking is going to be fixed in the client(this is just what i feel like they will be fixing don't take my word on it)...
1: Linesplit 
2: Mass disappearing when merging or popspliting 
3: Twerking (might already be fixed, I don't know)
4: The zoom when you're big sometimes you cant see either above you or below you (major problem)
5: Name when you have a long skin name on a server where you can only have 15 characters in the name space you cant have your full name(Fix: put the <skinname> in play one time die then take <skinname> out and add your name, skin should still be there after you took out the <skinname>)

**Comment by Agarian** [comment]
Mass dissapearing is fixed

**Comment by Agarian** [comment]
The zoom issue already happens in agar

**Comment by LegitSoulja** [comment]
I have fixed the skin issue, which now skins won't interfere with your actual name.

Disappearing cells, and mass was caused by server side.. Not the client.

Twerking is caused by server side aswell, but I think cleaning up the code, and have faster loading will fix this issue maybe...

Linesplit, i have no clue on how to manage that.

Zoom, Automatic zooming is now a thing. When you get big quick, or small your zoom will determine your cell sizes. You can still use scroll and things to zoom, but i figure it was kindof annoying when using the client and then joining the game with a weird zoom.

**Comment by Souf123** [comment]
i am so excited

**Comment by AlexandriteErikParacelsus** [comment]
Seems like megabytes fixed the linesplit on his server
