### ISSUE TITLE
Requested features.

### ISSUE THREAD

**Issue by hlevine9** [AJS-development/Ogar-unlimited#1414]
I have some requests.

Can you add a minimap to the game, and/or team tags so if you want to play with friends, you know where to locate them.

Can you add a URL field to the game? I want the process of creating/using a custom skin easier. If this isn't possible, can you make it possible to upload skins to a website, like gota, and choose your own skin name for it?

Thanks!

**Comment by AgarioIsBest1602** [comment]
That would be AWESOME!

**Comment by bangana** [comment]
agree.

**Comment by UltraSirius** [comment]
IT IS AWESOME Agree For It Minimap Would be easier! So Players Can Find u easier!

**Comment by NatsuTheGreat** [comment]
Now now, no one's going to be working on this :/

**Comment by hlevine9** [comment]
I mean, not right now, but if you happen to get the chance to, please do so. I was also wondering if you could do them.

**Comment by RevivedSol** [comment]
@legitsoulja already told that he can't make minimap

**Comment by CodingKuda** [comment]
@RevivedSol i thaugh he quit...

**Comment by LegitSoulja** [comment]
@RevivedSol looking at the original client It did in fact had a build on minimap, which I could see if I can re-add and make it work with the client. Since the days of re-writing I think I kindof understand how to make minimaps work.

Note due to the current position of ogarul I won't be developing anything anymore if this project gets deleted. Therefor, if this project compaign succeed, then I'll proceed into finishing up the new client.
