### ISSUE TITLE
Random Hack Attack :(

### ISSUE THREAD

**Issue by reaper999666** [AJS-development/Ogar-unlimited#1416]
So while i was in my server all the sudden the server was being spammed with bots and it lagged so bad
and all these bots were joining and i think someone was hacking cuz the bots joined so fast the chat was being spammed with Welcome Ogarbot.ovh to the server! and in the console it spammed Message sent to all i need this fixed

**Comment by NatsuTheGreat** [comment]
You might wanna take out that welcome message, or make it a private message for the use so that it doesn't spam the public chat.

**Comment by reaper999666** [comment]
Thats not gonna resolve it :/

**Comment by NatsuTheGreat** [comment]
That will fix the spam...

**Comment by UltraSirius** [comment]
It Will Fix The Spam @LegitSoulja Is now Creating A Ban System Who Is Creating Fake Bots. I Heard RAC Royalty He Is the creator Of Fake Bots. he Dont Create The Bots In Node.js But In C Language

**Comment by LegitSoulja** [comment]
Actually, there is really no way for me to identifying bots on the client because bots isn't connecting to the client, but connecting via sockets. 

The only way to fix this is to limit the connection per ip's, and also track mouse positions from bots, which there is an automatic ban system. 

MassStart on the other hand, prevents people from joining twice with the same connection if they aren't in game. This was a method I used to prevent people from constantly joining feeding themselves. Maybe MassStart can help big time in this case.

**Comment by LegitSoulja** [comment]
Bots, and DDOS attacks what what needs to be prevented. I have a few ideas onto doing this, but for now. I don't know if this project will be continued or not, but if it does the new project will hopefully contain these features. I hate it for a spoil Apple ruin everyone else's picnic.

**Comment by NatsuTheGreat** [comment]
>Even changing it to pm the console will still be spammed since it's a command being executed.

It'll help against the bots spamming the public chat.
