### ISSUE TITLE
Owner's Attitude

### ISSUE THREAD

**Issue by CheikoAsami** [AJS-development/Ogar-unlimited#1422]
If your going to have this attitude about feeling this project is useless, your giving up on the people who still use this, the people who can't make an account and tell you this, the people who finally found joy again in agar.io and your just going to take that away from the people who still care and want this project to be continued? I can't donate because i'm flat poor, if your just going to slowly wrench this from me and everyone else's grasp, then your taking away something i truly loved to have... Seeing the days count down really hurts, it really does... I had all of this in my head last night, when I came to find out that i could not move, if i moved the slightest I would hurt my neck badly, i was so angry because i could not say this to you... Please for my sake and many others out there keep this project going, it's not a useless cause, its the only thing that can allow you to host private servers that I know of and with crying out loud minions for a change! Don't give up, when you find a time of hopelessness ask the community in assistance, see if someone could help along side you or take the project over for you in the mean time, so then when you have a vacation or something you can take a break from this... And when you come back you may find the inspiration to continue....

**Comment by Andrews54757** [comment]
@CheikoAsami I am not hopeless, I just want to not waste any time. You condemm my actions, now you must answer my questions. Brace yourself and answer, and see the reason in my actions.



1. Who created ogarUL?
2. Is this project supposed to be permanent or experimental?
3. Does playing the game achieve anything in life?
4. Are you learning anything?
5. If you get depressed about shutting down ogarUL, then what is the condition of your life?
6. What is greater, Humanity or your comforts
7. Were you the one who created minions and other features?
8. Where were you in this project when I created it?
9. Do you have the authority to control this project?
10. Can you create something similar to this?
11. Is your wisdom and knowledge greater than mine?
12. Do you even care about others?
13. Even if you were broke, couldn’t you convince others to help?
14. Do you have a family? are you neglecting them because of this?
15. Who are you that I must waste my time with?
16. What is the meaning of life to you? Games?
17. Have you ever seen the affliction in third world countries?
18. Have you ever accepted their children in poverty?
19. Have you ever visited and care for children in an orphanage?
20. Why should you love ogarUL?


Answer these questions. All of them, and then I will consider you.


Andrews54757,
"My word is law in my projects"



OTHER DEVS: do not delete anything here

**Comment by LegitSoulja** [comment]
Preach it. + 1

**Comment by Megabyte918** [comment]
Closing this for now...

**Comment by LegitSoulja** [comment]
@Megabyte918 you've made the wrong decision. There's people waiting for answers, like me and Andrew. Open it back and let Andrew close it when this is done. Everyone needs to see this, and not be hidden. Thanks.

**Comment by Luka967** [comment]
Here to put up yet another argument.
Even this 10 mass cell is primarily working for Ogar, I still check OgarUL from time to time.
The #1417 title was attracting to me, because Andrews was inactive with his #1196 for quite some time (I wish I know how OgarUL is made to finish that PR) and I was waiting to test after the release.
@Andrews54757, Ogar was made as an open-source **non-profit** organization. It has been made on a free platform with free tools, and zero dollars were invested on it (not counting ogarproject.com). You know about that post on ogarproject.com explaining scams on Ogar. I don't know about others, but I'm in a second world country with strict parents, and not so much money.
**My life is on first place**. If I, you, he, she, it, apache helicopters, and anybody else don't have that much money to spend, at least **fund for own life** to be at lease somewhat happy and healthy. Unless you're really that generous that you're slowly killing your health, and yourself. Seriously.
If YOU, and ONLY YOU want to move on with your life, **don't hurt innocents**. Nobody here active and constantly checking GitHub did something wrong to you, and did not affect your life. If YOU, and ONLY YOU want to help charity, **don't shut down a NON-PROFIT project just because YOU want to move on with your life**.
Yes, I know about the lives of poor people in third world countries. Yes, I know that they are not properly funded. I don't care how much you or anyone else has the will and money to let it for charity. I don't, and I don't care for charity for now.
I am also on the brink of stopping Ogar development but I do it for **fun**. Programming is a job when it's worked under a company. Programming is a hobby when you're doing it at home because you don't have anything else to do. I feel that you're counting OgarUL contributing as a job now.
And seriously, **$2000 with a crowd of a bit over 110 people**? You've now assumed that everyone contributing here is from the top countries and that he/she/it/helicopter will all donate $50. You've gone too far.
I'm 13 years old. I'm speaking serious.

**Comment by NatsuTheGreat** [comment]
Damn you're 13 and program? Same here. :)

**Comment by LegitSoulja** [comment]
There's more people than your calculations over 110. There's more than a thousand people who play ogarul. You can't say that based on github, when majority of them just come here, take this project and claim it as there's. As to what Andrew said some people only care for themselves and not nobody else. 

Yes, this project was experimental, and to your question to why this even exist is located here https://github.com/AJS-development/Ogar-unlimited/wiki/How-Ogar-Unlimited-came-to-be.

Yes, this is non-profit but who said anyone here is gaining revenue? Andrew is providing something everyone loves with his own time now and this project has became bigger, and more frustrating. So I kindof understand why Andrew wants to see if the community would help out with donations. It's best to see someone helping someone else atleast for something they want. 

Mainly, if this goes as planned, ogarul will be made better, and by looking at it, no we won't be part of Ogar license which I hope not. Since ogarul was built from Ogar and how badly Ogar was developed I can see why it might be a good idea to start over fresh.

$3000 is a goal, but it's not like we are forcing everyone. A little help from the community is better than trying to force people to donate. We are not, but more than likely trying to get the message out to everyone then hopefully see the results at a later time.

**Comment by Luka967** [comment]
@LegitSoulja 
I'm excluding everyone that only used this project as download-and-run. We don't care about the author stealers, as the name suggests, won't do anything else for this project.
If he keeps getting frustrated for his work, why didn't he leave already? He could have just said that he's dropping out and nobody will bat an eye this much.
He is forcing us. He's practically made a kickstarter campaign on something that has already been finished; yet, no money, no release. OgarUL "to be made better" by doing this is simply morally wrong for a free project.
Ogar was and is still functional.I know I've badly messed it up for "performance" but I'm messing it up even more for the sake of making it more productible. The same happened here, you here still know what is where in OgarUL, I still know what is where in Ogar.

**Comment by Andrews54757** [comment]
@Luka967 I created this project so I can LEARN JavaScript and Nodejs. NOT to create a game. This project came to me when I couldnt DO SOMETHING in my PROGRAMMING CLUB. It is so I CAN LEARN AND SO THAT OTHERS CAN LEARN. Now, OgarUl turned far much bigger than I expected and it is a horrible experience.  HUNDREDS OF THOUSANDS, EVEN MILLIONS come here and our websites. DID I WANT THIS PROJECT TO BE THIS BIG? DO I WANT THIS TO CAUSE GAME-ADDICTION? ABSOLUTELY NOT!  Also, the community is very burdensome, not just for me. This is why I will create a better one only available to select people (still free), with no support

**Comment by Luka967** [comment]
@Andrews54757 Well that makes sense, yet it is still pointed at you.
I wanted to make the facts about this decision clear - now that you've seen it, no more explaination is needed.

**Comment by Megabyte918** [comment]
Guys, can we please take 1 moment to appreciate this awesome linesplit
![epiclinesplit](https://cloud.githubusercontent.com/assets/17245196/17843135/75c6f102-67f8-11e6-8536-6f3f41bc6b4b.gif)

**Comment by RevivedSol** [comment]
@andrews54757 you said this project is created for you to learn js and coding ? Well if that is I want to join in the project. This year I'm 13 and when I was 9 in already interested in coding and js but no one could teach me how to code and there's no way my parents gonna sent me to a coding school or class since they want me to study well.. :'(

**Comment by LegitSoulja** [comment]
@RevivedSol better and more efficient work is needed. I was 7 when I started java. Up until then C/.NET language, JavaScript, and jQuery, and php I had used a lot. Apart from that I've have dealt with nodejs for a quite some time it feels.

OgarUl is going to need a lot of work and stability. I don't think you'll be up too the challenge

**Comment by SharkFinPro** [comment]
@RevivedSol I was in the same position as you, but i started with Khan Academy :/ and now i just taught myself PHP a couple weeks ago

**Comment by Agarian** [comment]
I started JS at 12, I'm 14 (and a half) now.

**Comment by SharkFinPro** [comment]
I started JS at 9, I'm 12 (and a half) now.

**Comment by NatsuTheGreat** [comment]
I started JS at the start of the summer.

**Comment by SharkFinPro** [comment]
:/
NOOB XD
lol

**Comment by mrzack506** [comment]
html + css at 6 (scratch), js at 10, learning c++ at 13

**Comment by NatsuTheGreat** [comment]
@SharkFinPro I am pretty sure that withing those three months, I have learned much more than you, and pretty sure that I am a lot better than you :)

**Comment by LegitSoulja** [comment]
Let's not start arguing over who has more knowledge and who doesn't. 

Technically, nobody can judge unless work is shown.

**Comment by RevivedSol** [comment]
I really want to learn coding :'(

**Comment by NatsuTheGreat** [comment]
We can compare what we learned on the weekends, when I am not busy.

**Comment by firelightning13** [comment]
Wow, you guys are very lucky though. Too bad I'm really bad at programming... (at least I know a bit of basic javascript, html and css, from online course).

```javascript
$("im").trigger("ed");
```

**Comment by LegitSoulja** [comment]
@NatsuTheGreat waste of time,

@firelightning13 only thing you have to do is play around with code, discover it for yourself. 

Don't go learn, or use those schools, but use Docs, if you ever too need help.

**Comment by LegitSoulja** [comment]
Learn a little bit about code, then read docs. 

That's the way I taught myself. I started from Java, then I caught on to other languages really easily

**Comment by UltraSirius** [comment]
I am 13 Years Old. I am Starting To Scratch Javascript And C++ at 13 LoL :/

**Comment by LegitSoulja** [comment]
@UltraSirius I'd never go to javascript, then c++.

I stared with JAVA, then web development, then I learned C language from vb.net up to c++. 

Taking those steps you'll understand stuff better than to be switching all over the place. And also, stick to one language. Javascript isn't that important. You can't do as much with it, but NodeJS kindof stepping into the concept of OS js operating which is cool, but i still prefer c#. 

Object oriented will be common to you afterwards.

**Comment by SharkFinPro** [comment]
@LegitSoulja Why Not Javascript then C++?
Thats what im gonna do

**Comment by SharkFinPro** [comment]
or any c languages :/

**Comment by LegitSoulja** [comment]
@SharkFinPro Then if you learn c++ don't learn until you learn vb.net...

It's more easier to learn object oriented program much more. I've helped many people in the years, even friends and yes they know quite a-bit about alot of languages so far, and use them quiet often :).
