### ISSUE TITLE
AudioAPI

### ISSUE THREAD

**Issue by Tokoagar** [AJS-development/Ogar-unlimited#1424]
Where can I find audioapi? to install it?

**Comment by LegitSoulja** [comment]
:/

How do you even know about AudioAPI? Of course you read about it on the issue, and I do confirm that I did say

> **AudioAPI will not be released until the new client is released because it will be useless to have on the plugin library.**

Therefor, there's NO PLACE to get this plugin, except from a few people who already has it, but we made an agreement not to share the plugin, and where the new client is hosted. I doubt i'll even be finishing the new client because of ogarul conditions now. Can you do me a favor and read and pay attention next time? Unnecessary issues sometimes do get annoying.
