### ISSUE TITLE
Someone made bots going to this website :/ http://www.royaltyartz.tk/

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1430]
i banned them, but then my internet crashed (i have a g router) so i forget what the IP was

**Comment by AgarioIsBest1602** [comment]
Please close this issue this doesnt have any sense we cant help u sorry

**Comment by firelightning13** [comment]
@AgarioIsBest1602 Then don't say anything if you don't know about this if you think "this doesn't make any sense to you", unless you're owner or contributor or have been experienced by this issue.

@SharkFinPro You might ask LegitSoulja for this

@LegitSoulja

**Comment by LegitSoulja** [comment]
Yea, this post is out of this project scope. Learn PHP is all I have to say.

**Comment by LegitSoulja** [comment]
You shouldn't use a universe site page counter because it doesn't collect visitors information.

You need to prevent duplicate counts. Make your own system to do so. I've shared my PHP script with someone for having a live online counter for a site if you are interested. You'll have to find that issue though. 

Good luck

**Comment by SharkFinPro** [comment]
i found the IP
40.76.205.29
(they came back)

**Comment by LegitSoulja** [comment]
@SharkFinPro Just listen to yourself right now. You are complaining abouts "BOTS" on your website. This has nothing to do with OgarUL.

**Comment by Agarian** [comment]
Actually i think he means the bot names were "http://www.royaltyartz.tk/"

**Comment by SharkFinPro** [comment]
These Were the bots' names: royaltyartz.tk
This was the bots' IP adres: 40.76.205.29
THIS IS ALL OGARUL @LegitSoulja ( @Agarian You were right)

I have seen them on other servers too, so please ban them from visiting ogarUL

**Comment by LegitSoulja** [comment]
Well, there's nothing I can no longer do about it. 

I'll handle it for once and for all if in future ogarul

**Comment by systemroot** [comment]
@LegitSoulja maybe can you tell me how can i get how much players are in server? 
i was trying with curl to get information from ip:88 just for online players. but isn't working (or i'm doing something wrong) i'm getting all information not just players!
Thanks,

**Comment by LegitSoulja** [comment]
Sessions, PHP, MySQL to store SESSION ID's and reset time.

Run cron every 5 minutes to remove those from database that's pass time that hasn't been refreshed..



Or, with jQuery, you could Ajax stat server and parse its content to get players, or use statistics backend

**Comment by LegitSoulja** [comment]
url: http://stats.ogarul.tk
data: {livejson:null}

Ajax, get return of json p.

Don't know how long I'll have this open for, but it'll still be there in use of statistics servers

**Comment by LegitSoulja** [comment]
And you could use php, but for some odd reason I never can't get fsock to connect with nodejs services.

**Comment by systemroot** [comment]
@LegitSoulja i just want to put some stats at one gamepanel for ogarul servers :/ 
Not for all servers which are at stats. just for servers created from my panel.
If you can make any "Embed" option for server which will be on stats this will be awesome so we can embed it in website, also i can put it at my gpanel!
this is what i think to do
![](http://image.prntscr.com/image/b27ca8edf98b455fa6e612611b9a2e17.png)

**Comment by LegitSoulja** [comment]
About embedding no I will not do. That's lack of security.

You can get just your server using the method above, just pull out the correct gameuid, and get the information.

**Comment by LegitSoulja** [comment]
I don't understand how you want your own panel created servers, but them embed. 

I need more clarity..

**Comment by systemroot** [comment]
how will create servers? ogarul will copied directly from github, i have create one bash script for this
then database will updated and server will be in gpanel client homepage. also is an ajax ftp to edit game files.
and ogar console which you created will be pre installed. because client will not have access from ssh!
i can add RCON like cs 1.6 to manage server but i don't want to give full access so Your console is cool and i can hide some commands!
but without any stat in gamepanel will be only server name.. and i don't know how can i get online players with ajax, haven't work with it before!
for embed i was thinking example
*after server is created and stats plugin is installed*
`<script src="http://stats.ogarul.tk/embed.js" type="text/javascript"></script>`
`<div id="stats"></div>`
and div output will be just **"5 / 64"** // this is needed for my panel!
the panel which i'm using is bright game panel but i have edit it.

But that embed is an good think. example if you can, you can create one embed option for servers which will show one banner
**`Server name :`**
**`ip and port`**
**`live players bots.` **
`and one button "play" with href : play.ogarul.tk/?ip={ip}`
and we can embed in our websites // also we can get more players/visitors!
I think for this is needed to create ogarul query as you already have make for stats.ogarul.tk now you just need embed option!
well is just an suggestion, you know better than me :confused: 
if you will make other releases for stats, another suggestion is to create user support login/register
and one page to put their servers. 
for example user can put their server information and server will be in homepage 
ex : http://severus.coderior.com/ <-- this is an cool monitor with conf verifier. 
so you can maybe find an way to verify is stats plugin installed or not before to publish server. 
example in gametracker we need to change hostname to verify before to add server..
is just an idea!

**Comment by LegitSoulja** [comment]
I created the entire stat system using PHP. So therefor, i have a created a way to PARSE data from mysql into JSON, which you can obtain, and do what you want with the data.

```
$.ajax({
    url: "//stats.ogarul.tk",
    data: {livejson:null},
    type: "GET", // required
    dataType: "json",
    success:function(d){
        for(var i in d){
            if(d[i].gameuid == "myuid"){
                 // i = your server index
            }
        }
    }
});
```
###### Objects
* gameuid
* gamemode
* host
* serverPort
* statPort
* serverBots
* serverName
* serverPlayers

I will not make this work easy for you making the stats embedded. Statistics may not even be the same in the future, or may not even exist in the future. It's either im done with statistics, or re-make it better which I still haven't done yet.

**Comment by systemroot** [comment]
@LegitSoulja Thank you :+1: :+1: 
And we all use statistics to find a server, don't close it please :confused:

**Comment by SharkFinPro** [comment]
Dont close statistics :D

**Comment by LegitSoulja** [comment]
@systemroot that's if the project closes, then yes the client and statistics will be closed aswell,

then if this project continues, then everything will be re-created. Even the client, and statistics.

**Comment by SharkFinPro** [comment]
@LegitSoulja can you just ban the ip i gave you from visiting ogarul.tk?
that way i can close this issue

**Comment by LegitSoulja** [comment]
@SharkFinPro No, because a bot doesn't directly connect to the website, it connects to the websocket from somewhere else. Bot's has no interference with the client, and will still be able to join your server..

This will have to be added to the global server uniban, not client bans.

**Comment by SharkFinPro** [comment]
but cant you just ban that IP from visiting the website at all

**Comment by LegitSoulja** [comment]
Yes, but those are bots. They don't connect to the site, they connect to your server ip and port 443.

**Comment by SharkFinPro** [comment]
:o: i get it now

**Comment by SharkFinPro** [comment]
should i close this issue now?

**Comment by LegitSoulja** [comment]
Apparently. To block that, apply put that ip in your uniban text file.

**Comment by SharkFinPro** [comment]
ok

**Comment by SevenSlayy** [comment]
cant you just
`ban 40.76.205.29`

**Comment by LegitSoulja** [comment]
I'll try to make a PR

**Comment by SharkFinPro** [comment]
should i close this yet?

**Comment by LegitSoulja** [comment]
Agarian should've been did that, but yea close.

**Comment by systemroot** [comment]
An fast way to ban permanently 
**`ip route add blackhole 40.76.205.29`**
Use in terminal not ogarul console
