### ISSUE TITLE
I Have Question (I Know its Not Related but IDK) 

### ISSUE THREAD

**Issue by UltraSirius** [AJS-development/Ogar-unlimited#1433]
Hey Guys I have Some Few Question To have:

1)i dont have budget to host my ogar server, But my spec Are 4GB Ram (DDR3) Intel I3-2100 3.10GHz With 2 Cores, 4 Logical Processor Also Video Memory Up to 1682MB(I Dont Have GPU) My Graphics Card Is Intel HD Family (is it recommended or just right?)
 
So How Many Can I Handle Players?  Even My Hardisk speed only 5.9 With Internet Speed Of 3MBPS Router G (Maybe idk) 

Is There Any Free Host For Ogar And/Or VPS? (yes/no and how/why?)

2) I been Concerned About Raphy Server. Its Like its hosting limit has reach (Means he has only 1Month For hosting his ogar server) For 1 week i dont see he open the server (Let him stop giving up!) 

NOTE: Dont Excuse me for negative comments (no badwords no sexual words)    cuz i know who is the real one who can answer... i repeat Dont Excuse me for negative comments (no badwords no sexual words)

**Comment by LegitSoulja** [comment]
@UltraSirius Raphy sometimes host with his own servers, same as I do but i don't host anymore.

Raphy is also using ovh hosting, maybe you could? It's no free but i know he pays roughly around $20 a month. He is also running other servers other than ogar, so you might not see his server up unless he plays it that day until it goes down again i guess because of a server restart, or crash..

Your specs are somewhat good enough to host ogar, but nobody can determine if it'll be good or not unless you host and figure it out. Some people have weaknesses in handling players(bad connections), or handling bots(memory wasting, or limited memory), vice versa. 

For me, with good graphics, and a GPU, or overclocked processor will work great. I've had no problems.

**Comment by LegitSoulja** [comment]
You can get free hosting for sometime with DigitalOcean IF promo is still available. I wrote a documentation about how to obtain, and use ogarul here https://github.com/AJS-development/Ogar-unlimited/wiki/Digital-Ocean-Setup

**Comment by UltraSirius** [comment]
@LegitSoulja Last Question (Close It For 3 Dayz If No One Answers) Is There A Glitch Called a Virus Glitch thingy I saw Raphy He Uses Virus Glitch, But i Want it also in my server. Could you know how to do it?

**Comment by LegitSoulja** [comment]
Virus glitch?

**Comment by LegitSoulja** [comment]
Raphy doesn't even code lol, maybe the config setup up is somewhat bugged for that to happen. Idk

**Comment by UltraSirius** [comment]
But In torto server when i eject mass near virus and shoot it where the ejectedmass is pointed. its getting bigger and bigger and then when you eat it you will get big.

**Comment by LegitSoulja** [comment]
@UltraSirius no, i recommend liquid coolant, or risk of a motherboard fry, and kfc baked house.

**Comment by RevivedSol** [comment]
@LegitSoulja lol it looks like you're trying to scare @ultrasirius

**Comment by Agarian** [comment]
lol closing this for now
