### ISSUE TITLE
How to create my public server?

### ISSUE THREAD

**Issue by iTzArrowFx** [AJS-development/Ogar-unlimited#1437]
Sorry for mi bad inglish, i'm spanish :+1:  :+1: 
I'm ask for create my PUBLIC server, Without hamachi,
Its possible?, As?

**Comment by LegitSoulja** [comment]
@iTzArrowFx no, and hamachi sucks

**Comment by UltraSirius** [comment]
i am using hamachi. @iTzArrowFx You need To Host Your Server Or Buy A VPS. (I Am Right)

**Comment by LegitSoulja** [comment]
*Vomits* You didn't have to TELL me what hamachi was, which I kindof already know but I don't use it nor have a use for it.

Hamachi is mainly used for those people who can't port forward, but isn't mainly used for port forwarding!. It's basically a VPN like said.

When you host Ogar, connections go from your computer -> to hamachi service -> then the connected users. And back from connected user -> to hamachi service -> then back to your computer.

That's the reason why connections are soo slow when using Hamachi. It's not supported for running servers(Game Server), but only is supported for running services BEHIND your network.

Either, you can use your router, or buy a new supporting router to port forward, or talk to your ISP, or buy hosting. Those are your only options.

Otherwise, i wouldn't spend money on buying a VPS just for ogar servers, unless you are dedicated to maybe lets say, run multiple servers, or plan on having a full ogar gaming website similar to http://agariohub.net

**Comment by bangana** [comment]
try nitrous.io it has 50 hours + there are offers to get more hours/buy :p

**Comment by AlexandriteErikParacelsus** [comment]
^ cough cough use codenvy

**Comment by RevivedSol** [comment]
Just get a router that has port forward feature

**Comment by LegitSoulja** [comment]
Or use dd-wrt software. But only with knowledge.

**Comment by Jhair2015** [comment]
ver este vídeo ;)

https://www.youtube.com/watch?v=nH-GmWd5gdU

**Comment by fayizan** [comment]
Now Its Easy to create your own public server with https://agarsrv.net  based on slots, Try it

**Comment by Agarian** [comment]
closing for now.
