### ISSUE TITLE
Possible tropical storm to hit Florida

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#1444]
I may not be online for a while, due to the fact that I have to prep for 
`Tropical Storm 9`, it is currently said that Florida will take a direct hit. It is said that this storm, even as a `tropical depression`, has up to 10 inches of rain. Those who live in central, or especially northern Florida, should stay indoors. You can check out [The Weather Channel's report](https://weather.com/storms/hurricane/news/tropical-depression-nine-tropical-storm-hurricane), or News 13 (for brighthouse users), or any other news related channel or radio station. 
**`This is it's location as of 8/30/16:`**
![tropicaldepression9](https://cloud.githubusercontent.com/assets/15255724/18113033/aca75cbc-6efa-11e6-951f-673ed1b4237e.jpg)
Florida's already getting hit by the outer bands of the storm. But who knows, it could miss, but as of right now, Florida is in the storm's collision course. And school is still going to be open (Typical :neutral_face: ) 
Now, i need to go to bed. See you later.

**Comment by LegitSoulja** [comment]
@Agarian if the storm happens over night then no you won't go to school. Only time school will closed if the past storm was bad(Where transportation in limited in some areas), or it snows (Which it will never snow in the south again). 

Global warming is going on aswell with the ozone. There's a lot of things people really need to look at but nobody never really pay attention.

**Comment by LegitSoulja** [comment]
Global warming is what will cause El Niño I'm the future. And it will be the worst storm every.

Am I ready? No. 
Is it friendly? Hell no. 
Will there only be one? Nope. There can be multiple, constantly.
What's the worst? Rain every day and nigh non stop.

**Comment by Agarian** [comment]
I've experienced 7 days of snow in Michigan's upper peninsula (while visiting family, i was 6 at the time)

**Comment by LegitSoulja** [comment]
How many feet of snow? I bet you was buried inside your house

**Comment by Agarian** [comment]
I think like 5 or 6 idk

Florida is damned
The USA is damned
The Earth is damned 
All because the human race didn't give a damn.
- Agarian

**Comment by Agarian** [comment]
Mother Earth, Mother Earth, take the seed and give it birth.
Father sun, gleam and glow, until the roots begin to grow.
Sister rain, Sister rain, shed your tears and swell the grain.
Brother wind, breathe and blow, and then the grain will start to grow.
Earth and sun and wind and rain, bring to life the growing grain.
Take these away and what do we gain?
Simply nothing but pure pain.

**Comment by LegitSoulja** [comment]
Yes. Indeed you know, I know. More.

Finally!. someone who actually understands this culture, and there life conditions and situtations, and how this world/earth is becoming shit because of Humans. There's no stop for people to having kids, but there SHOULD BE. 

According to actual facts, you should only have a child when you are married to someone. That's how most people now are f***ed over, and now got baby mamas, kids, and or abandoned kids that really should've never happened(No harm or offensive way). Population is exceeding because of generation teens don't know how to have an intercourse properly without causing accidents, and or not even using protection to prevent it from happening. If you don't want to have guardianship over someone yet then you know you might want to wrap more than once because you may not know how to use your junk correctly.

With that being said, and subject changing to this world, WATER in the future will be a main probably. Crops, food, vegetables will become a problem. Food meats will get poisoned, and or maybe sick. Especially if it goes through processing then you might as well just give people bad food.

Warm climates, sea levels increasing, water is getting got. Eventually fish will be hard to obtain. May even die out. Some fish can't outstand the hot climates. Therefor eating good fish may not even be a thing. UNLESS fish are being breaded else where, but then it would be FISH, SEAFISH. It would then be consider Tish. Tank Ish. Cause it'll taste like ish, from a tank.

Nobody said this earth will last long. Look how long it have has lasted. many many many x90 centuries yes. This might just be the final days of destruction's, and even soon possibly wars which will ever be worser to this word because of humans. We don't get along. This is just how this world is. Especially racism.

Alot of things is going on man.. I just sit back, watch things that's going on and hope it gets better, or not actually happen, or hope people start to realize. If people are to stupid to not realize and realize at the last minute then we are f***ed. 

But no doubt that this is all being staged. Or not even cared about by anyone. Not even the states, nor our shitty governments. Who is even there to go too for help? Nobody. You might as well be on your own. Let's just say you are in control and can do whatever you want to do. Just don't go on a killing spree.

Ever watched **I Am Legend?**. This is how this world might turn up too, but extra hot climates, and barely good pollution to breath in, or may not even a place we could ever live in if it gets bad. But just image if you was the last survivor?

Have you ever just sat down and thought about life? 

> Yes. Makes you want to cry and ask why am I here in the begin with? to just get pain?. Even though, life feels like a game being played. Nobody is winning. Everyone is losing. Eventually for kids, it seems like its a horrible thing. But when you get older you will realize LIFE may not be so important after all. Maybe for some people.

**Comment by UltraSirius** [comment]
Check This: https://en.wikipedia.org/wiki/Tropical_Storm_Hermine_(2016) Might it will be like 90KM From tampa but i will landfall at Florida. Peace.

**Comment by agariotips** [comment]
@LegitSoulja What you said is 100% true, humans were a mistake. If what some conspiracy theorists say (humans come from mars) is true, then it should've stayed like that. We're mass leechers of Earth, with 37 years left until oil is gone and the fact that in circa 15 years Earth could just be a wasteland of what humans have done to it. War is caused just by 1 lie. If you have ever seen **The Giver** or have read it, humanity should be somewhat like that. Areas around Greenland where polar bears and other animals live is slowly melting due to global warming. Some say that there should've been an Ice Age and that global warming stopped it. We're so greedy. We eat and use resources that isn't necessary to keep creating more unnecessary items. Life as a human is not important to me. I don't care if I die. 6,635,872 lethal poisonous chemicals released this year. In a couple 1000 years, (if we dont kill eachother), earth will be like mars, a carbon dioxide atmosphere with barely any life. Like Einstein said, 

> I know not with what weapons World War III will be fought, but World War IV will be fought with sticks and stones

We are a mistake.

**Comment by Agarian** [comment]
The storm passed lol
