### ISSUE TITLE
SINCE NO-ONE EVER LOOKS AT THE PLUGIN PAGE I'M POSTING THIS HERE:

### ISSUE THREAD

**Issue by SharkFinPro** [AJS-development/Ogar-unlimited#1452]
IN the Statistics plugin, the customdomain/whatever thing works fine...but could you add a custom port, because this:
node1.beta.codenvy.com:35157
leads to this:
node1.beta.codenvy.com:3000

**Comment by Agarian** [comment]
Are you going to tell me how to connect to the server via codenvy or not?

**Comment by Megabyte918** [comment]
@Agarian come on discord

**Comment by LegitSoulja** [comment]
You mean default port 443 leads to 3000? Then that's fine. It should work.

**Comment by LegitSoulja** [comment]
@SharkFinPro just set statistics to debug mode (1)
then line 264 in index.js of Statistics
```
statPort: stats.gameServer.config.serverStatsPort
```
change **stats.gameServer.config.serverStatsPort** with the port you want to use

**Comment by SharkFinPro** [comment]
ok

**Comment by SharkFinPro** [comment]
@LegitSoulja Ok, now it works but it apears red on Statistics, but when i click on it (on statistics) i can join it :/

**Comment by LegitSoulja** [comment]
Well maybe you shouldn't use codenvy demos

**Comment by LegitSoulja** [comment]
If codenvy site disallows stats.ogarul.tk GET connecting then that will be a problem.

**Comment by Agarian** [comment]
@LegitSoulja you know that Ogar-Plus thing that you made connectable through http://play.ogarul.tk
? I found it.

**Comment by LegitSoulja** [comment]
@Agarian ? cool

**Comment by systemroot** [comment]
this is because docker do port forward 
example your private server port is 443 , your public server port will be 5555
and stats will get the port which you have wrote at advConfig.ini
so you'll need to make stats to get port 5555 not port from advConfig.ini. 
for this only legitsoulja can help maybe there is any way example to wrote in advConfig.ini 
"statsporttest = 5555" 
and to make stats to get **statsporttest** not **serverPort**
btw i think this isn't possible.
only if in stats will be one option "custom port" as it is for "custom ip/domain"

**Comment by LegitSoulja** [comment]
@systemroot ^ I already showed him about using a custom port. The thing is that you shouldn't use codenvy test services with Statistics.
