### ISSUE TITLE
How this is possible?

### ISSUE THREAD

**Issue by arxn** [AJS-development/Ogar-unlimited#1462]
"ANIMATED SKINS"

IS POSIBLE ON THE CLIENT OF OGARUL?

https://www.youtube.com/watch?annotation_id=annotation_2204377&feature=iv&src_vid=UmgaM302AsE&v=IH8ucuT1e44

**Comment by rydens** [comment]
Those seem to just be examples, for someone's video...

**Comment by arxn** [comment]
PLAYING WITH CUSTOM SKINS

https://www.youtube.com/watch?v=EepAGdPtZhM

**Comment by LegitSoulja** [comment]
It's possible, but if you're thinking about doing this with agario clone it'll need some work done.

It's possible to use gif images and change the skin every frame in the gif. Of course it'll have to transition smoothing which there are some ways.

Maybe I'll expirement with it with the new client I'm re making. Recreating the normal skins will be pain since there's over 200 skins. I'll work with a few skins, it'll be rare, just because if all skins were animated then that will not look pretty, and your memory will not like it).

**Comment by arxn** [comment]
you can do your work public? @LegitSoulja  thanks.

**Comment by LegitSoulja** [comment]
@arxn Maybe... Or, i'll provide ways onto how to animate your skin using your own client. 
Just remember (Incase you want to accomplish this on your own)

* GIF(Contains frames, multiple frames which displays the animation when played)

> With javascript you should be able to get each frame in the gif, then when the skin is chosen, all the frames will loop through starting with 0, to the end of the frame, the back again to 0. You could use some fading effects to make the transition look smoother instead of having frames change without it looking unrealistic.
