### ISSUE TITLE
you've made a big mistake.

### ISSUE THREAD

**Issue by locktrap** [AJS-development/Ogar-unlimited#1463]
it was wrong to ban agarian over **your** opinion. i side with retslac on that fact. i also did heard miniclip didn't seem to listen to the community, and i'm afraid the same has happened here. it's torn the community apart at the mercy of this charity thing. this is your fault andrews. and i don't care/wanna hear what you have to say as an argument. i'm all ears for those who agree with me.

**Comment by LegitSoulja** [comment]
It's not **Andrew's** fault **Agarian** is banned, it is not **Andrew's** fault that this community is tearing apart. There's a reason behind everything. You can't be a witness if you weren't part of what happened to **Agarian**, and or why Ogarul is the way it is now. 

I don't have much say, and I don't have a side, im just myself. If you look at what **Agarian** was saying, then you should know as him being part of AJS, he wasn't being a good sport, and was not following the rules, which if you are an AJS member, then you should be polite, follow rules, and not cause trouble, which Agarian disobeyed all. There's a time and place for actions, but due to his actions, and due to the state of ogarul it was seen as if he was selfish, and or didn't like what was going on and didn't care about anything. But, he didn't have to act the way he was just because of it. Not only that was the first offense, but there was multiple cases, but nothing was never said about it, until Andrew actually realized his behavior and finally dealt with it.

Due to Ogarul, he should've know that he could've lost his part of being with AJS. Andrew noted plenty of times about removing people who didn't know anything, and dealing with people using profanity, and not being respectful to each other. Just because you are part of AJS doesn't mean you can do anything you want. If so, everything would be chaos, and if people came here and seen the chaos then we will look bad as to not having respectful members. If you go to any other issues of a repo, you would not see anything like that unless there was a reason for it. But other than that, it was not caused for at all.

I'm sure Andrew doesn't want to argue about this neither since it has happened, and cannot be undone(Since he removed his account anyways). He even said plenty of times that he will leave AJS, so who is really upset? No one. Agarian wanted to leave anyways, so that day was his day. I hope that since this happen he will find something else better to do, other than wasting time here. 

And last again
(**This project was experimental. Never meant to be lasted forever**). Atleast this project will hopefully be recreated better, but if issues like this about (Not caring) or (Not having to hear what someone has to say) really make someone not care about a thing. If you don't care, what make someone else want to care? They'll just give up completely and leave everything behind hopeless, with no return.

**Comment by LegitSoulja** [comment]
@locktrap and that's real homie..

--
@Andrews54757

**Comment by Andrews54757** [comment]
^^^^


Exactly.
