### ISSUE TITLE
UPDATE THE VERSE(world wide message)

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#149]
![updateverse](https://cloud.githubusercontent.com/assets/15255724/13376165/6344846a-dd81-11e5-8de7-ae71de3b8f3e.jpg)
my friend on discord wont stop talking about it, as he dont know what to do, he thinks he still has to update

**Comment by hassanila97** [comment]
HAHAH LOL "fuck andreus"  lol :)

**Comment by Agarian** [comment]
idfk what his problem was xD

**Comment by Agarian** [comment]
i muted him for it lol

**Comment by Andrews54757** [comment]
I feel tempted to publically humiliate your friend . Lol

**Comment by Agarian** [comment]
Lets not make matters worse lolol

**Comment by Andrews54757** [comment]
I want to send this as a world wide message. `Hello, i have heard that someone (dragoner) on discord insulted me because of this reason: Why does it say you cant use update command after i updated. My response: ARE YOU DUMB, IT IS NOT A UPDATEMESSAGE IT IS A GENERAL MESSAGE. UPDATEING HAS NOTHING TO DO WITH IT. AND WHY WOULD YOU THINK THAT? BECAZ YOU ARE DUMB, DUMB DUMD!`

**Comment by Andrews54757** [comment]
Lol

**Comment by Agarian** [comment]
OMFG I CANT XD
