### ISSUE TITLE
Anybody, can you make a hide and seek gamemode?

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#240]
This is how i would want it

Either like blockhunt in minecraft or hide and seek like agariomods

It's been forever since this request but I think it is possible.
To help, I added the blind command as a example on blinding certain people

**Comment by Megabyte918** [comment]
i dont know much about javascript... or how to code this stuff... but couldn't you just use the timer and properties from the zombie mode (so that you would have a timer counting down the seeker and other cells not on the seekers team wouldnt be able to eat eachother) to help with a new one? and i imagine adding the "spam q to sprint" thing from agariomods would be pretty easy because you could just have it increase the playerSpeed in gameserver.ini for a brief moment, but then again im not sure what im talking about cause im a noob at this stuff :p

**Comment by firelightning13** [comment]
@Megabyte918 And a few more things, the virus should change the virus transparency when you're inside it and use a mech like blind command to blind seekers when counting down :+1:

**Comment by Megabyte918** [comment]
yes exactly

**Comment by XtremePlayzCODE** [comment]
Yess!

**Comment by Andrews54757** [comment]
il do this as soon as im done with the bigger things

**Comment by Megabyte918** [comment]
kk good luck m6
