### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Agarian** [AJS-development/Ogar-unlimited#279]
![bug](https://cloud.githubusercontent.com/assets/15255724/13913797/58cd971e-ef20-11e5-9fc4-68d15ec4af68.jpg)
when vps is 1

**Comment by Megabyte918** [comment]
Read the error

**Comment by Agarian** [comment]
lol fail

**Comment by Megabyte918** [comment]
Haha happens to me too sometimes

**Comment by Agarian** [comment]
i noticed lag actually seems to be getting worse instead of better...

**Comment by Agarian** [comment]
i used to be able to handle 20 bots easily, not anymore

**Comment by Megabyte918** [comment]
What are the specs of your computer? I put 3gb of ram into my server and I can run 60 bots

**Comment by Agarian** [comment]
i have 4gb ram and (i think) a slow processor

**Comment by Megabyte918** [comment]
Same! Okay so what I did was I went into the src folder, shift+right clicked and selected "open command window here" then I entered this command, `node --max-old-space-size=3072 index.js` (this made my server run on 3gb of ram instead of 512mb and it sped up my server by 2x. im on vaca right now so no is using my comp so I made it use 3 out of 4 cuzynot xD

If you want to do the same just do `node --max-old-space-size=(insert size in mb) index.js`. nodejs uses 512mb by default. I think theres a way to make a bat file out of this but im too lazy to lol

**Comment by Megabyte918** [comment]
@Andrews54757 maybe add a config that lets you change the amount of ram in mb your server runs on?

**Comment by MichaelLeeHobbs** [comment]
@Megabyte918 not sure you can do it from inside of node. Likely just have to do it at the command line. I'll look into it latter.

**Comment by Megabyte918** [comment]
Sweet :)

**Comment by Agarian** [comment]
there is a way to do so

**Comment by Agarian** [comment]
cd [src folder path]
node --max-old-space-size=3072 index.js

**Comment by Megabyte918** [comment]
Or just edit the start.bat and change the line that says "node index.js" to that command

**Comment by Agarian** [comment]
about:
> node --max-old-space-size=3072 
is there a way to do this in c9?

**Comment by firelightning13** [comment]
Have u tried it yet?
c9 has 1gb

**Comment by Megabyte918** [comment]
probably but you wont get much out of it. i dont think you can get over 1gb because then you wont have enough ram left to run the rest of the server xd
