### ISSUE TITLE
Which gameserver.ini is being used?

### ISSUE THREAD

**Issue by markelite** [AJS-development/Ogar-unlimited#328]
This might be silly but I'm confused as to which gameserver.ini file takes precedence? there's one in the root folder i.e. `/home/user/gameserver.ini`, another one inside the Ogar-Unlimited folder itself `/home/user/Ogar-Unlimited/gameserver.ini`, and another one inside the `/src` folder `/home/user/Ogar-Unlimited/src/gameserver.ini`.

I edited the one in `/home/user/gameserver.ini` to change the gameserverport to something else but it didn't work, tried the one on `/home/user/Ogar-Unlimited/gameserver.ini` and it worked, but I have no idea which of them is being listened to. :-P right now I have to edit all of them to make changes which is very inefficient, and I'm probably shouldn't be touching two of those files.

**Comment by firelightning13** [comment]
did u run `sudo node src/index.js` or `cd src` then `sudo node index.js`

**Comment by markelite** [comment]
I run `sudo node index.js` inside the `/home/user/Ogar-Unlimited/src` folder, so I guess that's the same as running 'sudo node src/index.js'

**Comment by MichaelLeeHobbs** [comment]
@markelite yes. The gameserver.ini that is being ran is the one in the folder from which you ran the server. That is something that is being addressed, so we wont have this confusion in the future.

**Comment by Andrews54757** [comment]
@MichaelLeeHobbs didnt we get rid of this issue in dev?

**Comment by MichaelLeeHobbs** [comment]
@Andrews54757 not yet. I need to figure out a solid way to detect which folder the server gets called from and then change that to the correct folder or make it so that we dont care what folder we get called from so long as we can figure out where our root folder is ie someFolder/src Then need to make sure everything use that rootDir for loading files like gameserver.ini, skins, etc
