### ISSUE TITLE
Minion issues

### ISSUE THREAD

**Issue by XtremePlayzCODE** [AJS-development/Ogar-unlimited#446]
1. How to change what you add on to your name when you press Q? The B is kind of annoying me and I would like to change it to M

2. Minions spawn WAYY too close to master

3. Minions only go one direction when master dies and makes the master gain really fast

**Comment by Andrews54757** [comment]
The b is because at first, minions were just bots and if you did the command, the server bots would turn into minions so I thought "Bots" and that is where it came from. Now, minions are separate from bots so I should change it to M but i can't as every manual and youtube videos  (theres a lot) has B in it. I also cannot make it a config as config.ini only supports numbers


The second issue is not a problem for me as it is actually good. Spawning is random so probabilistically, if you have like 100 minions, some will spawn close


3. I know about it and I made it like that so it even works when spectating

**Comment by XtremePlayzCODE** [comment]
But I would like to know how just because. I tried looking throught every file and couldnt find where it changes the name to have a B. Also, when the minion's master dies, can't we just kill the minions, and to change the spawning close by we could have a config for that as you like it. It's just when I'm like 200k mass I just see no minions and they are all in between my cells.

**Comment by Andrews54757** [comment]
it changes to b in the op.js file (if you updated) i porposly made the minion/op functions hidden

**Comment by XtremePlayzCODE** [comment]
Ok thank you sooo much Andrews!
