### ISSUE TITLE
I have CD-ed the SRC folder and i still have an error.

### ISSUE THREAD

**Issue by elitajmx** [AJS-development/Ogar-unlimited#459]
Cannot find module brace-expansion.

What shall i do now?

**Comment by Andrews54757** [comment]
Delete node_modules. do it again

**Comment by elitajmx** [comment]
Ok thank you :+1:

**Comment by elitajmx** [comment]
Doesn't work again

**Comment by elitajmx** [comment]
i tried everything, help?

**Comment by Andrews54757** [comment]
mabye try redownloading ogar ul

**Comment by firelightning13** [comment]
Nope, it doesnt work...

**Comment by Andrews54757** [comment]
ask creators of npm

**Comment by Agarian** [comment]
and youre sure nothing is missing in package.json?

**Comment by Megabyte918** [comment]
it works fine for me

**Comment by elitajmx** [comment]
i tried redownloading but it doesn't work:/

**Comment by Agarian** [comment]
Like i asked, could something possibly be missing in package.json?

**Comment by elitajmx** [comment]
what package.json?? i don't know what should be missing there are millions of stuff

**Comment by Andrews54757** [comment]
there should be a package.son file in the folder that holds src

**Comment by elitajmx** [comment]
ohh yeah what do i do with it ^^

**Comment by Andrews54757** [comment]
whats the folder name that holds the src folder?

**Comment by firelightning13** [comment]
Hmm why it doesnt work fo me? I have package.json, clean-installed, didn't modify anything.

**Comment by Andrews54757** [comment]
this is really a problem with npm, not ogarul. ask the creators of npm

**Comment by elitajmx** [comment]
how do i ask them or what wtf

**Comment by firelightning13** [comment]
@elitajmx I fixed it! It was a missing file. Do this:
`npm install brace-expansion` then `npm install inflight`

**Comment by Agarian** [comment]
Its not in package.json then.

**Comment by elitajmx** [comment]
awesome thanks

**Comment by elitajmx** [comment]
bot spawn in top left still

**Comment by MichaelLeeHobbs** [comment]
Couple things here: First we dont directly use brace-expansion or inflight. These are used by something we use. Thus they should not be in our package.json. Likely what happened is that one of the libraries we used updated their requirement and made a mistake. Or even more likely one of the libraries our libraries used made a mistake. If you a good read on how this can break the internet check out http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/

Second, package.json should live in the same folder the src lives in, not inside src. In other words package.json is a peer of the src folder.

Third, I'll take a look at our package.json and make sure we are using specific library version and not "latest" or something like "2.0.+" this will avoid the issues of John having a working build because he hasn't ran npm install in months and Jill downloading OgarUL and doing npm install and getting different libraries than John, and thus a broken build.

**Comment by Megabyte918** [comment]
@elitajmx the spawning is fine4me

**Comment by firelightning13** [comment]
@MichaelLeeHobbs Ok, that make sense now, thanks for the information
