### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by LegitSoulja** [AJS-development/Ogar-unlimited#482]
![error1](https://cloud.githubusercontent.com/assets/4976824/14939626/dc8af0dc-0f0b-11e6-8a77-c8e56721450d.PNG)
![error2](https://cloud.githubusercontent.com/assets/4976824/14939627/dc96b9c6-0f0b-11e6-8388-fdf1f173fad9.png)

**Comment by MichaelLeeHobbs** [comment]
Whatever IDE you are using is not setup for ES6. Also you IDE is not recognizing console.log which is a core JS function. Google how to setup you ide.

**Comment by LegitSoulja** [comment]
My IDE is fine, its first time using it. Plus IDE is nothing wrong. I really dont need the syntax that comes, but every time I run this I get this error.

> src\index.js:3
> const Readline = require('readline');
> ^^^^^
> SyntaxError: Use of const in strict mode.
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:906:3

Ive tried everything. My IDE is fine.

**Comment by Agarian** [comment]
have you tried removing the const? i dont get that error.

**Comment by LegitSoulja** [comment]
Yes, but const and let is all over the file. That is mainly giving errors

**Comment by Agarian** [comment]
maybe remove 'use-strict'?

**Comment by LegitSoulja** [comment]
@Agarian 

```
src\index.js:7
let controlServer = new ControlServer(VERSION);
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
```

**Comment by Agarian** [comment]
:expressionless:

**Comment by MichaelLeeHobbs** [comment]
@Agarian dont bother, your wasting your time.
@LegitSoulja This is the last time I am going to help you. From this point forward if you have a pointless issue it will just be closed.

In your screenshot it is CLEAR that your IDE is not setup for ES6 otherwise it would not be giving errors on ES6 key words of let and const. For example in WebStorm my IDE of choice I have to tell it I am using ES6 or it will give me lot of errors.

Secondly, you should run: node -v  if it returns something other than v5.9.0 then you should run: npm install n -g followed up by: n 5.9.0

If you are not capable of that then you are not capable of running OgarUL

**Comment by Agarian** [comment]
i think he FINALLY took care of it #483
