### ISSUE TITLE
Growth

### ISSUE THREAD

**Issue by Logan7432** [AJS-development/Ogar-unlimited#560]
Im on the newest verison of ogar unlimited and i got a question about the grouth. What numbers do i put for the growth chance?

**Comment by Logan7432** [comment]
And also how do i use cloud9 to host my server

**Comment by LPArigma** [comment]
@logan do not open multiple issues! look at the issues there is a guide to hosting it on c9.io!

**Comment by problemsofworld** [comment]
close this   issues read before making  issuse

**Comment by LegitSoulja** [comment]
@Logan7432 Well, I'm guessing you mean food growth right? 
FoodMass = The amout of mass you get when you eat the food
FoodMassGrow = The max of the growth of the food
FoodMassGrowPossibility = The chance of getting a growth of the food
FoodMassLimit = The amout of mass that a mass could have, depending on growth when eaten

**Comment by Logan7432** [comment]
yes, food growth but it what do i put for possibility? should i put something like 85%? And the c9 instructions didnt seem clean so i wanted a better explanation

**Comment by LegitSoulja** [comment]
@Logan7432 I really don't use c9 because I have proper hosting services. So im unfamiliar with c9. There's a issue about c9 and if you need help then ask a question there and maybe someone with experience with c9 can help you. And yes, you would set your possiblity high if you want your food to grow.
