### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by Logan7432** [AJS-development/Ogar-unlimited#561]
Why when i use this server my chat on my client dosnt work? Please fix this!

**Comment by LPArigma** [comment]
@Logan7432 if you didnt notice you should read the issues before making issues, your consiquence will most likely be a 1 month ban from this repo, unless @Andrews54757 is felling nice

**Comment by Logan7432** [comment]
@LPArigma Jeez..... A ban would be kind of harsh considering its hard to find something related to my issue when theirs so many issues. Instead of being rude about this maybe you can **helpful** and guide to to that other issue so i can read about the problem instead of posting another issue.

**Comment by LegitSoulja** [comment]
@Logan7432 The thing is people been making unrelated issues, when the issues are there you can find on your own if you need help. We try to help everyone as much as we can but it just gets annoying sometimes. Andrew just had got enough of the issues so now you have to follow a guideline now on what you need help with because people dont get to the point of what they actually talk about.

**Comment by Logan7432** [comment]
@LegitSoulja  Thanks, thats a way better explained then @LPArigma said.

**Comment by Andrews54757** [comment]
@Logan7432 I am gonna let this slide, but dont do it again
