### ISSUE TITLE
Our Website

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/Ogar-unlimited#646]
We have a website now! at http://forum.ogarul.tk. Thanks to @LegitSoulja

**Comment by Andrews54757** [comment]
Devs, make an account and I will makr you as mod

**Comment by LegitSoulja** [comment]
We should replace the issues to the forums?

**Comment by bean07** [comment]
@Andrews54757 i can support u a vip website,not free

**Comment by Megabyte918** [comment]
@LegitSoulja "whats 9+10" it was 21 really lmfao

**Comment by LegitSoulja** [comment]
@bean07 there's no such thing as a vip website...

And, we are good. I have proper hosting.

**Comment by bean07** [comment]
i mean the .com or the international .tld u will hard to ceo with .tk

**Comment by PrinceDark9243** [comment]
i cant able to enter the question 9+10=19 dosent work but when i entered 21 it worked lol!

**Comment by LegitSoulja** [comment]
@bean07 SEO is not hard for a .tk domain lol. A domain is a domain. .com, or .net is not technically a vip domain/website like you was saying.

You just need to know how to work with SEO

**Comment by bean07** [comment]
i know its not vip,i just wrong but,,, the tk is free so google down that rank,trust me!

**Comment by PrinceDark9243** [comment]
lol

**Comment by LegitSoulja** [comment]
@bean07 Yea, but you have to work with SEO. .tk is not like a blacklisted domain extension.

and besides, I don't think SEO is even necessary right now. I could easily get a domain, but just for now its ogarul.tk

**Comment by bean07** [comment]
oh,ok

**Comment by hassanila97** [comment]
But... why not get a .io    it sounds very nice and easy to remember and attractive... Also as @bean07 said .TK wesites are considered shit by Google.

**Comment by LegitSoulja** [comment]
@hassanila97 .io. Do you know exactly what .io is mainly for? I know .tk is bad because eventually it could be stolen or taken if it comes popular. But the thing is that this isn't nothing special like a game website, or something that will create revenue from, nor nothing that will become popular. 

And besides, this is just a domain for starters. We would eventually get a domain that's not .tk and definitely not .io. Just think about what tld uses are for exactly. .io would be more expensive than a .net, .com, and .org, and OgarUL is just for a client, and a forum as of right now. 

I see .tk as a private domain because it's a thing many people won't look at. I personally use it because currently it's free, and sometimes you just want a domain so you can work before you actually buy one. Many people do the same thing. Why buy a domain when a site might not even become successful?

There's many pros and cons but just chill. It's not a big deal. I have a website myself with a .info & .net extension. I've used tk, and actually got a decent rank on google with it. You just have to work with SEO to actually get full potential in a domain.

Just like agariohub.net.. Look at the domains he has been through. I recently got agariohub.tk from him since yes he used it way before his site became popular and he had to change. He's making profit off of something. Ogarul.tk isn't.

It's just pointless as of right now.

**Comment by LegitSoulja** [comment]
But if it's really a huge big deal, then buy a domain for yourself, and we'll just close OgarUL.tk and transfer domains easily without problems. 

But until then, I will get one when its time, and if really needed.

**Comment by firelightning13** [comment]
Cool website. Now put the link in README.md

**Comment by ErikParacelsus** [comment]
Lol the question 9+10 is broken when i type the answer (which is 19) it said Wrong answer!!1!1!!

**Comment by Agarian** [comment]
its a joke of the 9+10=21 meme, type 21 as the answer xD (that was actually the first answer i put)

**Comment by GrevenSound** [comment]
Hey, I have three free .com domains, because I bought a hosting server, and service gave three free .com .net or .biz  if u want to use, because, i only use an own domain, yet existing...
![ogarul](https://cloud.githubusercontent.com/assets/17583489/15416706/c73fb6ea-1e24-11e6-9bbb-baadaa8a9867.jpg)

**Comment by GrevenSound** [comment]
![ogarul2](https://cloud.githubusercontent.com/assets/17583489/15416810/b1fb4384-1e25-11e6-9247-0b007f7b07a6.jpg)

**Comment by LegitSoulja** [comment]
@GrevenSound I'll decline your offer. Much appreciated though.

**Comment by LegitSoulja** [comment]
Your registrar doesn't provide private registration. Therefor your offer is declined.

**Comment by LegitSoulja** [comment]
A domain will be privately registered next week. I take back about someone else buying a domain since it was a huge deal.

And plus, it will take months before a domain gets unlocked and transferred

**Comment by GrevenSound** [comment]
@LegitSoulja Well, I don't know about register and that's stuff, but, if you say that my register doesn't provide that, well, I only want to help... :).

**Comment by LegitSoulja** [comment]
@GrevenSound yea I totally understand but do you understand about domain transfers?. One of AJS dev's will have to have ownership of the domain so that we can control it. It will be too much work for someone else to register it, and something we won't have full access too. Anything could happen.

**Comment by GrevenSound** [comment]
@LegitSoulja Well, I understand, actually, I had a big problem with a domain that was not in my name, I finally stole the web site, the domain was not in my name ...
Had not thought of that.

**Comment by LegitSoulja** [comment]
@GrevenSound on the safe side, i wouldn't even register a domain with your information. That's why private domain registrations are the best.

**Comment by Martinali12** [comment]
10+9=21

**Comment by bean07** [comment]
LOL

**Comment by Lukkez** [comment]
![image](https://cloud.githubusercontent.com/assets/15003706/15456430/10d21e6a-2046-11e6-8526-731e19f3e717.png)
**Lol**

**Comment by Lukkez** [comment]
It's correct (just a meme with the website xd)

**Comment by LegitSoulja** [comment]
@Lukkez there's 4 answers to that question actually

**Comment by Agarian** [comment]
kden

**Comment by bean07** [comment]
9+10=21 http://play.ogarul.tk/form.html
