### ISSUE TITLE
Public-Private Servers

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#652]
Hi!
Im wondering if someone can tell me a step by step process on how I can make my friends join the private server using c9.io i know c9.io but I dont really have knowledge in coding thanks :)

**Comment by LegitSoulja** [comment]
@SorryAgario I would no longer recommend c9 due to there policy that was cleared up a few days ago. 

- You cannot run servers/services using c9. c9 was said to be only for running test applications, and for development use only. If you are caught running Ogar servers on c9 you will get banned without a warning and you'll loose everything you accomplished. Do not use c9 unless you are willing to get banned. 

- Me personally would not tell you how to use c9 as its against there TOS, and I don't even use c9 for myself. 

Check out the issue **c9 is no VPS** for more information.
