### ISSUE TITLE
Glitch With The New Update

### ISSUE THREAD

**Issue by SorryAgario** [AJS-development/Ogar-unlimited#656]
So today, i updated my ogar-unlimited server from 16.3.5 to 16.5.5 and then I used the ip "agar.io/?ip=127.0.0.1:443"  and I used the "Bagar Helper" extension to help in connecting to the private server. So, I pressed Play so it was just a black circle showing up in the middle then when i zoom in, the circle is glitching out. So I went to the "play.ogarul.tk" client and pasted my local server ip which is "127.0.0.1:443" I was able to spawn in but the problem is that my blob was weirdly too small and it looked like it had 1 mass and when I reach the top border Its comes back to normal or its gonna fix by itself by suiciding a couple of times then as time pass by The game will be kinda playable then when I reach the bottom wall, my camera glitched out after a few seconds.... Also I typed <Kraken> then the Kraken skin didn't even show up. (this was before i spawned)..... I checked the config and the verification was set to "= 0" And I used Node.js Version 5.90 and saw not even a single error while installing the dependencies.... What do I do to fix this "glitch"? Help or a Reply Is Much Appreciated
-SorryISplit

**Comment by SorryAgario** [comment]
Also I updated the server so I can split the bots with E and Eject mass with R which makes it more fun!
![default](https://cloud.githubusercontent.com/assets/19484292/15431804/4eb090d2-1e60-11e6-8824-00cd8886003e.png)

**Comment by SorryAgario** [comment]
![default](https://cloud.githubusercontent.com/assets/19484292/15432063/76d1ef1a-1e61-11e6-88af-436247538dc4.png)
![default](https://cloud.githubusercontent.com/assets/19484292/15432071/7c6d92e4-1e61-11e6-9e31-c43fb42b0904.png)

**Comment by LegitSoulja** [comment]
@Andrewss15457

@SorryAgario 
By now, OgarUL still won't be able to connect to http://agar.io/. The main reason why you couldn't use agar.io was because you never changed the packet version. OgarUl uses a custom client and therefor does not work unless you change the packet version to work with non moddified clients. The extension I cannot help you with.

I have also experienced the same problems with the client over at http://play.ogarul.tk but it only happens once in a while

### Bugs

- **Updating Cells**:
When joining, packets never update which leads you with a 0 mass bug and you don't become normal unless you eventually run into the border, or collect food on the way to the border. P.S .. When this happens, you cannot move at all until your cell turns back normal

- **Border Bounce Cell Attack**:
If a cell run into the border they just don't stop. They get teleported back into the grid, and glitches all around. Kindof weird and I hate it 

> I have experienced more bugs, but kindof forgot what they where. I have not played ogarul within a few days.

**Comment by Martinali12** [comment]
use the old packet and that's it.

**Comment by LegitSoulja** [comment]
@Martinali12 well these bugs are with the ogarul custom client. Changing back to the old packets and using the custom client won't work, or unless you meant change them for agar.io which I have already said.

**Comment by SorryAgario** [comment]
So What should I do to prevent these bugs?
