### ISSUE TITLE
Can't Connect After Privater Server Fix

### ISSUE THREAD

**Issue by KyraCloud** [AJS-development/Ogar-unlimited#678]
http://prntscr.com/b6qhxr 

^ there's the link to the picture

**Comment by Martinali12** [comment]
add description before making issues or get banned !

Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

What game mode were you in when you had the issue?

What version are you on?

What command did you type if any?

You must have a description as well

Most common questions involve:

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

Can you make minions split by pressing E or R key?
A: NO, as agar.io client doesn't support those keys. Otherwise, you would need to use another client, and that is illegal.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by LegitSoulja** [comment]
@KyraCloud Please downgrade your node version to 5.9.0. Run the command

> sudo n 5.9.0

check your node version afterwards

> sudo node -v

If windows, don't include sudo since you should already have root perms.

**Comment by Megabyte918** [comment]
Im starting to get annoyed no one ever follows the guidelines

**Comment by KyraCloud** [comment]
@LegitSoulja thanks for help next time i wont repeat an issue.
