### ISSUE TITLE
HELPPP PLEASEEEEEEEEE

### ISSUE THREAD

**Issue by DTMClanDeveloper** [AJS-development/Ogar-unlimited#792]
i realllllllly need someone to give me a tutorial on how to set this up with koding IDE. I wanna make a clan server but i cant because im not experienced at all with koding so please make a tutorial STAT

**Comment by systemroot** [comment]
Tutorial is pretty simple. 
Install node js and follow 

do ``git clone https://github.com/AJS-development/Ogar-unlimited.git``
cd into src (ex: ``cd Ogar-unlimited/src``)
do ``npm install`` (npm install)
start the server (``sudo node index.js``) (to enable garbage collect do ``sudo node --expose-gc index.js``)
play using [play.ogarul.tk](http://play.ogarul.tk/) (Supported 100% Chrome Browser)
[Andrews54757 Tutorial](https://github.com/AJS-development/Ogar-unlimited/issues/729)

If you don't know how to install node, **Well let me google do it for u**. :smile: 
http://lmgtfy.com/?q=how+to+install+nodejs+on+ubuntu+14.04

If are you talking about kodingdotcom you will need to connect to your VPS. So Why do you need koding when you have Putty :question: 

If you are talking about beta koding. I Think this is not possible. Because to run Ogar you need 2 ports and in beta koding you have only one :cry: 

.. If you don't have a vps to run your Ogar server, Well take a look at http://agariohub.tk/ 
or http://rawclan.ml/ And you can play with ur team.

**Comment by DTMClanDeveloper** [comment]
can other people connect to it if i do this

**Comment by Megabyte918** [comment]
i dont think koding is supposed to be used as a free vps like this
