### ISSUE TITLE
Multiverse?

### ISSUE THREAD

**Issue by aqweqwel123** [AJS-development/Ogar-unlimited#992]
When i use multiverse create then do all that it creates the game but when i reload my page it says teams 2 when i click on it it doesn nothing, when i join by http://play.ogarul.tk/ the game is glitched

**Comment by PrinceDark9243** [comment]
me too some largest virus appear and disappear

**Comment by Andrews54757** [comment]
@LegitSoulja can you investigate? test out multiverse for me (im taking a break)

**Comment by LegitSoulja** [comment]
@Andrews54757 I don't see no problems what so ever.

**Comment by Megabyte918** [comment]
@aqweqwel123 make sure you have followed EACH and EVERY step correctly for setting up multiverse. See #729 for instructions

**Comment by genckaptan55** [comment]
I have the same issue too. I use client which i saw here but as @aqweqwel123 told nothing happens. Also at the console an error is threw about ogarconsole port usage which tells that port already in use that is 1000.

**Comment by LegitSoulja** [comment]
@genckaptan55 OgarConsole only work with the master server only. Due to the fact that multiverse create new instances of plugins, and OgarConsole can't re-run again on the same port. Therefor whilst using multiverse it's not possible to control other servers, and multiverse commands can't even be used.

**Comment by genckaptan55** [comment]
If multiverse is not work with others than i don't understand aim of it. Yeah i also recognized that it's not possible to change console port for different servers like team, exp etc. except the main one but however you can create, remove, select and also can manage via multiverse after selecting that server by the commands such as playerlist etc.

 What i am curious about is, is that causing the problem why i cant connect other created servers via multiverse? Because of that port problem? Do i have to use play.ogar.tk to use multiverse?

**Comment by LegitSoulja** [comment]
You don't have to use play.ogarul.tk, but you have to have the basic client that play.ogarul has with chat, macros, client settings, etc...

I'll take one more look at multiverse, because I don't use it I just run multiple servers. I know a few people have had problems.

**Comment by genckaptan55** [comment]
You run multiple servers by copying server files for each server i guess. How do you connect those seperated server to the same client? How do you set ip|port to the servers those are shown in the selection menu?

**Comment by LegitSoulja** [comment]
@genckaptan55 we don't discuss about clients. You need experience to do that. You can find a recent issue about this.
